const Map<String, Map<String, String>>
generatedPhraseOverrides = <String, Map<String, String>>{
  'fr': <String, String>{
    'Accounts, transfer, custom categories':
        'Comptes, transferts, catégories personnalisées',
    'Add Budget': 'Ajouter un budget',
    'Add Budget Goal': 'Ajouter un objectif budgétaire',
    'Add Plan': 'Ajouter un plan',
    'Add Planned Payment': 'Ajouter un paiement planifié',
    'Analytics event sent.': 'Événement d\'analyse envoyé.',
    'Backup failed: {error}': 'Échec de la sauvegarde : {error}',
    'Billing is disabled in offline mode.':
        'La facturation est désactivée en mode hors ligne.',
    'Biometric authentication failed.':
        'L\'authentification biométrique a échoué.',
    'Biometric is not supported on this device.':
        'La biométrie n\'est pas prise en charge sur cet appareil.',
    'Biometric Lock': 'Verrouillage biométrique',
    'Budget check completed.': 'Vérification du budget terminée.',
    'Cadence': 'Cadence',
    'Capture runtime errors and improve app reliability.':
        'Capturez les erreurs d\'exécution et améliorez la fiabilité de l\'application.',
    'Check Alerts': 'Vérifier les alertes',
    'Choose the language used across the app':
        'Choisissez la langue utilisée dans l\'application',
    'Cloud sync and online login are disabled. The app now works fully offline with local storage.':
        'La synchronisation cloud et la connexion en ligne sont désactivées. L\'application fonctionne désormais entièrement hors ligne avec le stockage local.',
    'Crash test logged.': 'Crash test enregistré.',
    'Crashlytics not configured yet. Add google-services.json and rebuild Android.':
        'Crashlytics pas encore configuré. Ajoutez google-services.json et reconstruisez Android.',
    'Create one-time or recurring plans (monthly, weekly, yearly) and process them when due.':
        'Créez des plans ponctuels ou récurrents (mensuels, hebdomadaires, annuels) et traitez-les à leur échéance.',
    'CSV export failed.': 'L\'exportation CSV a échoué.',
    'CSV exported.': 'CSV exporté.',
    'Custom Range': 'Plage personnalisée',
    'Disable PIN': 'Désactiver le code PIN',
    'Due date': 'Date d\'échéance',
    'Excel export failed: {error}': 'Échec de l\'exportation Excel : {error}',
    'Expense added from OCR.': 'Dépense ajoutée à partir de l\'OCR.',
    'Export CSV': 'Export CSV',
    'Global (All Categories)': 'Global (toutes catégories)',
    'Global Budget': 'Budget global',
    'Google Sheets export failed: {error}':
        'Échec de l\'exportation Google Sheets : {error}',
    'Import CSV': 'Importation CSV',
    'Invalid OCR amount.': 'Montant OCR non valide.',
    'Invalid PIN.': 'Code PIN invalide.',
    'Local Database': 'Base de données locale',
    'Lock Now': 'Verrouiller maintenant',
    'Mark all read': 'Marquer tout comme lu',
    'Monday': 'Lundi',
    'Month': 'Mois',
    'Monthly Limit': 'Limite mensuelle',
    'No budgets set yet.': 'Aucun budget n\'a encore été défini.',
    'No end date': 'Pas de date de fin',
    'No planned payments yet.': 'Aucun paiement prévu pour l\'instant.',
    'Notifications': 'Notifications',
    'OCR failed or canceled.': 'OCR a échoué ou annulé.',
    'OCR Result': 'Résultat OCR',
    'Offline First': 'Hors ligne d\'abord',
    'PDF export failed: {error}': 'Échec de l\'exportation PDF : {error}',
    'PIN': 'PIN',
    'PIN disabled.': 'PIN désactivé.',
    'PIN enabled.': 'PIN activé.',
    'PIN must be at least 4 digits.':
        'Le code PIN doit comporter au moins 4 chiffres.',
    'Premium expense manager.\nVersion 1.0.0':
        'Gestionnaire de dépenses Premium.\nVersion 1.0.0',
    'Pro Lifetime - {price}': 'Pro Lifetime - {price}',
    'Process Now': 'Processus maintenant',
    'Refresh Config': 'Actualiser la configuration',
    'Remote config refreshed.': 'Configuration à distance actualisée.',
    'Remove ads': 'Supprimer les publicités',
    'Restore failed: {error}': 'Échec de la restauration : {error}',
    'Save PIN': 'Enregistrer le code PIN',
    'Savings target': 'Objectif d\'économies',
    'Scan Camera': 'Scanner la caméra',
    'Scan Gallery': 'Galerie de numérisation',
    'Security Lock Enabled': 'Verrouillage de sécurité activé',
    'Send Event': 'Envoyer un événement',
    'Send Test Error': 'Envoyer une erreur de test',
    'Set PIN (4-6 digits)': 'Définir le code PIN (4-6 chiffres)',
    'Smart Tools Center': 'Centre d\'outils intelligents',
    'SMART User': 'Utilisateur SMART',
    'Spent': 'Dépensé',
    'Sunday': 'Dimanche',
    'Switch Wallet': 'Changer de portefeuille',
    'This app is no longer maintained since November 5, 2024.\n\nYou can continue using it, but it will no longer receive updates or bug fixes. Some features may stop working over time.\n\nRecommendations:\n- Back up your data regularly.\n- Consider an actively maintained alternative.':
        'Cette application n\'est plus maintenue depuis le 5 novembre 2024.\n\nVous pouvez continuer à l\'utiliser, mais elle ne recevra plus de mises à jour ni de corrections de bugs. Certaines fonctionnalités peuvent cesser de fonctionner avec le temps.\n\nRecommandations :\n- Sauvegardez régulièrement vos données.\n- Envisagez une alternative activement maintenue.',
    'Tools': 'Outils',
    'Transferred {amount} {currency} between accounts.':
        'Transféré {amount} {currency} entre comptes.',
    'Unavailable': 'Indisponible',
    'Unlimited bank accounts (more than 2 wallets)':
        'Comptes bancaires illimités (plus de 2 portefeuilles)',
    'Unlock with Biometrics': 'Déverrouiller avec la biométrie',
    'Unlock with biometrics or PIN to access tools.':
        'Déverrouiller avec la biométrie ou un code PIN pour accéder aux outils.',
    'Unlock with PIN': 'Déverrouiller avec le code PIN',
    'Upgrade to Pro to unlock OCR receipt scanner.':
        'Mise à niveau vers Pro pour déverrouiller le scanner de reçus OCR.',
    'Use fingerprint/face to protect tools.':
        'Utilisez l\'empreinte digitale/le visage pour protéger les outils.',
    'Week': 'Semaine',
    'Usage Reached {percent}%': 'Utilisation atteinte {percent}%',
    '{count} recurring expense(s) added automatically.':
        '{count} dépense(s) récurrente(s) ajoutée(s) automatiquement.',
    'Budget added for {category}.': 'Budget ajouté pour {category}.',
    'Spent {amount} this month.': 'J\'ai dépensé {amount} ce mois-ci.',
    'You used {spent} of {limit} spendable budget.':
        'Vous avez utilisé {spent} sur {limit} de budget disponible.',
    '{category} planned as {cadence} schedule.':
        '{category} prévu comme horaire {cadence}.',
    '{target} reached {percent}%': '{target} a atteint {percent}%',
    '{count} expense(s) synced to cloud.':
        'Dépense(s) {count} synchronisée(s) avec le cloud.',
    '{count} expense(s) loaded from CSV.':
        'Dépense(s) {count} chargée(s) à partir du CSV.',
    '{count} new expense(s) merged from cloud.':
        '{count} nouvelle(s) dépense(s) fusionnée(s) à partir du cloud.',
    '1) Budget Goals + Alerts': '1) Objectifs budget + alertes',
    '2) Planned Payments': '2) Paiements planifiés',
    '3) Offline Data Mode': '3) Mode données hors ligne',
    '4) Crash Monitoring': '4) Surveillance des plantages',
    '5) Analytics + Remote Config': '5) Analytique + config distante',
    '6) Biometric / PIN Lock': '6) Verrou biométrie / PIN',
    '7) OCR Receipt Scanner': '7) Scanner de reçus OCR',
    '8) CSV Import / Export': '8) Import / Export CSV',
    'Processed recurring items: {count}':
        'Éléments récurrents traités : {count}',
    'Last OCR: amount={amount} | date={date}':
        'Dernier OCR : montant={amount} | date={date}',
    'Budget Added': 'Budget ajouté',
    'Cloud Account Created': 'Compte cloud créé',
    'Cloud Download Complete': 'Téléchargement cloud terminé',
    'Cloud Upload Complete': 'Envoi cloud terminé',
    'Crash Test Sent': 'Test crash envoyé',
    'CSV Exported': 'CSV exporté',
    'CSV Imported': 'CSV importé',
    'Global budget': 'Budget global',
    '{category} budget': 'Budget {category}',
    'Logged In': 'Connecté',
    'Logged Out': 'Déconnecté',
    'Monthly on day {day}': 'Mensuel le jour {day}',
    'OCR Expense Added': 'Dépense OCR ajoutée',
    'One-time on {date}': 'Une seule fois le {date}',
    'Receipt Scanned': 'Reçu scanné',
    'Recurring Expense Added': 'Dépense récurrente ajoutée',
    'Weekly each {weekday}': 'Hebdomadaire chaque {weekday}',
    'Yearly on {month} {day}': 'Annuel le {day} {month}',
    ' â€¢ Ends {endDate}': ' â€¢ Fin {endDate}',
    '{schedule}{endDateText}. Last applied: {lastAppliedText}':
        '{schedule}{endDateText}. Dernière exécution : {lastAppliedText}',
    '{target} reached 80%': '{target} atteint à 80%',
    '{target} reached 100%': '{target} atteint à 100%',
    'Tools Guide': 'Guide des outils',
    'Start here: secure access, set budgets, automate plans, then use OCR/CSV.':
        'Commencez ici : securite, budgets, plans auto puis OCR/CSV.',
    'Budgets: {count}': 'Budgets : {count}',
    'Plans: {count}': 'Plans : {count}',
    'Unread: {count}': 'Non lus : {count}',
    'Budget Goals + Alerts': 'Objectifs budget + alertes',
    'Set limits and get alerts at 80% and 100%.':
        'Definissez des limites et alertes a 80% et 100%.',
    'Example: Food budget 300. Alert appears near 240.':
        'Exemple : budget nourriture 300, alerte vers 240.',
    'Create one-time or recurring expenses.':
        'Creez des depenses uniques ou recurrentes.',
    'Example: Rent 500 on day 5 every month.':
        'Exemple : loyer 500 le jour 5 chaque mois.',
    'The app works offline with local storage.':
        'L application fonctionne hors ligne avec stockage local.',
    'Example: add transactions without internet.':
        'Exemple : ajoutez des transactions sans internet.',
    'Monitor runtime issues and verify reporting.':
        'Surveillez les erreurs runtime et verifiez le reporting.',
    'Example: send one test error after release.':
        'Exemple : envoyez une erreur test apres release.',
    'Track usage and refresh live thresholds.':
        'Suivez l usage et actualisez les seuils en direct.',
    'Example: tap Refresh Config to load latest limits.':
        'Exemple : touchez Actualiser config pour charger les derniers seuils.',
    'Protect tools using fingerprint or PIN.':
        'Protegez les outils avec empreinte ou PIN.',
    'Example: enable biometric and set a 4-digit PIN.':
        'Exemple : activez biometrie et PIN 4 chiffres.',
    'Scan receipts and convert them to expenses.':
        'Scannez les recus et convertissez-les en depenses.',
    'Example: scan restaurant ticket then confirm amount.':
        'Exemple : scannez ticket resto puis confirmez le montant.',
    'Import or export transactions with spreadsheet format.':
        'Importez ou exportez les transactions en format tableur.',
    'Example: export monthly report or import CSV file.':
        'Exemple : exportez rapport mensuel ou importez un fichier CSV.',
  },
  'ar': <String, String>{
    'Finance Chatbot': 'شات بوت مالي',
    'Open Chatbot': 'فتح الشات بوت',
    '4) Finance Chatbot': '4) الشات بوت المالي',
    'Assistant is typing...': 'المساعد يكتب...',
    'Type your question...': 'اكتب سؤالك...',
    'How much incoming this month?': 'كم الدخل هذا الشهر؟',
    'How much did I spend this week?': 'كم صرفت هذا الاسبوع؟',
    'What is my net cashflow this month?':
        'ما هو صافي التدفق المالي هذا الشهر؟',
    'How much on food this month?': 'كم صرفت على الاكل هذا الشهر؟',
    'How many wallets can I use?': 'كم عدد المحافظ التي يمكنني استخدامها؟',
    'How do I change app language?': 'كيف اغير لغة التطبيق؟',
    'Current setup: {plans} plans, {budgets} budgets, currency {currency}.':
        'الاعدادات الحالية: {plans} خطط، {budgets} ميزانيات، العملة {currency}.',
    'Start here: secure access, set budgets, automate plans, then use chatbot, OCR and CSV.':
        'ابدأ من هنا: فعّل الحماية، اضبط الميزانيات، شغّل الخطط، ثم استخدم الشات بوت و OCR و CSV.',
    'Accounts, transfer, custom categories':
        'الحسابات والتحويل والفئات المخصصة',
    'Add Budget': 'إضافة الميزانية',
    'Add Budget Goal': 'إضافة هدف الميزانية',
    'Add Plan': 'إضافة خطة',
    'Add Planned Payment': 'إضافة الدفع المخطط',
    'Analytics event sent.': 'تم إرسال حدث التحليلات.',
    'Backup failed: {error}': 'فشل النسخ الاحتياطي: {error}',
    'Billing is disabled in offline mode.':
        'تم تعطيل الفوترة في وضع عدم الاتصال.',
    'Biometric authentication failed.': 'فشلت المصادقة البيومترية.',
    'Biometric is not supported on this device.':
        'القياسات الحيوية غير مدعومة على هذا الجهاز.',
    'Biometric Lock': 'قفل البيومترية',
    'Budget check completed.': 'تم الانتهاء من فحص الميزانية.',
    'Cadence': 'الإيقاع',
    'Capture runtime errors and improve app reliability.':
        'التقاط أخطاء وقت التشغيل وتحسين موثوقية التطبيق.',
    'Check Alerts': 'التحقق من التنبيهات',
    'Choose the language used across the app':
        'اختر اللغة المستخدمة عبر التطبيق',
    'Cloud sync and online login are disabled. The app now works fully offline with local storage.':
        'تم تعطيل المزامنة السحابية وتسجيل الدخول عبر الإنترنت. يعمل التطبيق الآن بشكل كامل دون اتصال بالإنترنت مع التخزين المحلي.',
    'Crash test logged.': 'تم تسجيل اختبار الأعطال.',
    'Crashlytics not configured yet. Add google-services.json and rebuild Android.':
        'لم يتم تكوين Crashlytics بعد. أضف google-services.json وأعد بناء Android.',
    'Create one-time or recurring plans (monthly, weekly, yearly) and process them when due.':
        'إنشاء خطط لمرة واحدة أو متكررة (شهرية، أسبوعية، سنوية) ومعالجتها عند استحقاقها.',
    'CSV export failed.': 'فشل تصدير ملف CSV.',
    'CSV exported.': 'تم تصدير ملف CSV.',
    'Custom Range': 'النطاق المخصص',
    'Disable PIN': 'تعطيل رقم التعريف الشخصي',
    'Due date': 'تاريخ الاستحقاق',
    'Excel export failed: {error}': 'فشل تصدير Excel: {error}',
    'Expense added from OCR.': 'تمت إضافة النفقات من التعرف الضوئي على الحروف.',
    'Export CSV': 'تصدير CSV',
    'Global (All Categories)': 'عالمي (جميع الفئات)',
    'Global Budget': 'الميزانية العالمية',
    'Google Sheets export failed: {error}':
        'فشل تصدير جداول بيانات Google: {error}',
    'Import CSV': 'استيراد ملف CSV',
    'Invalid OCR amount.': 'مبلغ التعرف الضوئي على الحروف غير صالح.',
    'Invalid PIN.': 'رقم التعريف الشخصي غير صالح.',
    'Local Database': 'قاعدة البيانات المحلية',
    'Lock Now': 'قفل الآن',
    'Mark all read': 'تحديد الكل مقروء',
    'Monday': 'الاثنين',
    'Month': 'شهر',
    'Monthly Limit': 'الحد الشهري',
    'No budgets set yet.': 'لم يتم تعيين ميزانيات بعد.',
    'No end date': 'لا يوجد تاريخ انتهاء',
    'No planned payments yet.': 'لا توجد مدفوعات مخططة حتى الآن.',
    'Notifications': 'الإخطارات',
    'OCR failed or canceled.': 'فشل التعرف الضوئي على الحروف أو إلغاؤه.',
    'OCR Result': 'نتيجة التعرف الضوئي على الحروف',
    'Offline First': 'غير متصل أولاً',
    'PDF export failed: {error}': 'فشل تصدير PDF: {error}',
    'PIN': 'PIN',
    'PIN disabled.': 'PIN معطل.',
    'PIN enabled.': 'تم تمكين رقم التعريف الشخصي.',
    'PIN must be at least 4 digits.':
        'يجب أن يتكون رقم التعريف الشخصي (PIN) من 4 أرقام على الأقل.',
    'Premium expense manager.\nVersion 1.0.0':
        'مدير النفقات المتميزة.\nالإصدار 1.0.0',
    'Pro Lifetime - {price}': 'Pro Lifetime - {price}',
    'Process Now': 'العملية الآن',
    'Refresh Config': 'تحديث التكوين',
    'Remote config refreshed.': 'تم تحديث التكوين عن بعد.',
    'Remove ads': 'إزالة الإعلانات',
    'Restore failed: {error}': 'فشلت الاستعادة: {error}',
    'Save PIN': 'حفظ رقم التعريف الشخصي',
    'Savings target': 'هدف التوفير',
    'Scan Camera': 'مسح الكاميرا',
    'Scan Gallery': 'معرض المسح',
    'Security Lock Enabled': 'تمكين قفل الأمان',
    'Send Event': 'إرسال حدث',
    'Send Test Error': 'إرسال خطأ اختبار',
    'Set PIN (4-6 digits)': 'تعيين رقم التعريف الشخصي (4-6 أرقام)',
    'Smart Tools Center': 'مركز الأدوات الذكية',
    'SMART User': 'المستخدم الذكي',
    'Spent': 'تم إنفاقه',
    'Sunday': 'الأحد',
    'Switch Wallet': 'Switch Wallet',
    'This app is no longer maintained since November 5, 2024.\n\nYou can continue using it, but it will no longer receive updates or bug fixes. Some features may stop working over time.\n\nRecommendations:\n- Back up your data regularly.\n- Consider an actively maintained alternative.':
        'لم تعد تتم صيانة هذا التطبيق منذ 5 نوفمبر 2024.\n\nيمكنك الاستمرار في استخدامه، لكنه لن يتلقى تحديثات أو إصلاحات للأخطاء بعد الآن. قد تتوقف بعض الميزات عن العمل مع مرور الوقت.\n\nالتوصيات:\n- قم بعمل نسخة احتياطية من بياناتك بانتظام.\n- فكر في استخدام بديل تتم صيانته بشكل نشط.',
    'Tools': 'الأدوات',
    'Transferred {amount} {currency} between accounts.':
        'منقولة {amount} {currency} بين الحسابات.',
    'Unavailable': 'غير متاح',
    'Unlimited bank accounts (more than 2 wallets)':
        'حسابات مصرفية غير محدودة (أكثر من محفظتين)',
    'Unlock with Biometrics': 'فتح باستخدام القياسات الحيوية',
    'Unlock with biometrics or PIN to access tools.':
        'فتح باستخدام القياسات الحيوية أو رقم التعريف الشخصي للوصول إلى الأدوات.',
    'Unlock with PIN': 'فتح باستخدام رقم التعريف الشخصي',
    'Upgrade to Pro to unlock OCR receipt scanner.':
        'الترقية إلى Pro لفتح الماسح الضوئي لإيصالات التعرف الضوئي على الحروف.',
    'Use fingerprint/face to protect tools.':
        'استخدم بصمة الإصبع/الوجه لحماية الأدوات.',
    'Week': 'الأسبوع',
    'Usage Reached {percent}%': 'تم الوصول إلى الاستخدام {percent}%',
    '{count} recurring expense(s) added automatically.':
        '{count} تتم إضافة النفقات (النفقات) المتكررة تلقائيًا.',
    'Budget added for {category}.': 'تمت إضافة الميزانية لـ {category}.',
    'Spent {amount} this month.': 'أنفقت {amount} هذا الشهر.',
    'You used {spent} of {limit} spendable budget.':
        'لقد استخدمت {spent} من {limit} من الميزانية القابلة للإنفاق.',
    '{category} planned as {cadence} schedule.':
        '{category} مخطط كجدول {cadence}.',
    '{target} reached {percent}%': 'تم الوصول إلى {target} {percent}%',
    '{count} expense(s) synced to cloud.':
        '{count} النفقات (النفقات) التي تمت مزامنتها مع السحابة.',
    '{count} expense(s) loaded from CSV.':
        '{count} النفقات (النفقات) التي تم تحميلها من ملف CSV.',
    '{count} new expense(s) merged from cloud.':
        '{count} النفقات (النفقات) الجديدة المدمجة من السحابة.',
    '1) Budget Goals + Alerts': '1) أهداف الميزانية والتنبيهات',
    '2) Planned Payments': '2) المدفوعات المخططة',
    '3) Offline Data Mode': '3) وضع البيانات دون اتصال',
    '4) Crash Monitoring': '4) مراقبة الأعطال',
    '5) Analytics + Remote Config': '5) التحليلات + الإعدادات عن بُعد',
    '6) Biometric / PIN Lock': '6) قفل البصمة / رقم PIN',
    '7) OCR Receipt Scanner': '7) ماسح الإيصالات OCR',
    '8) CSV Import / Export': '8) استيراد / تصدير CSV',
    'Processed recurring items: {count}':
        'العناصر المتكررة التي تمت معالجتها: {count}',
    'Last OCR: amount={amount} | date={date}':
        'آخر OCR: المبلغ={amount} | التاريخ={date}',
    'Budget Added': 'تمت إضافة الميزانية',
    'Cloud Account Created': 'تم إنشاء حساب سحابي',
    'Cloud Download Complete': 'اكتمل تنزيل السحابة',
    'Cloud Upload Complete': 'اكتمل رفع السحابة',
    'Crash Test Sent': 'تم إرسال اختبار الأعطال',
    'CSV Exported': 'تم تصدير CSV',
    'CSV Imported': 'تم استيراد CSV',
    'Global budget': 'الميزانية العامة',
    '{category} budget': 'ميزانية {category}',
    'Logged In': 'تم تسجيل الدخول',
    'Logged Out': 'تم تسجيل الخروج',
    'Monthly on day {day}': 'شهرياً في اليوم {day}',
    'OCR Expense Added': 'تمت إضافة مصروف عبر OCR',
    'One-time on {date}': 'مرة واحدة في {date}',
    'Receipt Scanned': 'تم مسح الإيصال',
    'Recurring Expense Added': 'تمت إضافة مصروف متكرر',
    'Weekly each {weekday}': 'أسبوعياً كل {weekday}',
    'Yearly on {month} {day}': 'سنوياً في {month} {day}',
    ' â€¢ Ends {endDate}': ' â€¢ ينتهي في {endDate}',
    '{schedule}{endDateText}. Last applied: {lastAppliedText}':
        '{schedule}{endDateText}. آخر تنفيذ: {lastAppliedText}',
    '{target} reached 80%': 'وصل {target} إلى 80%',
    '{target} reached 100%': 'وصل {target} إلى 100%',
    'Tools Guide': 'دليل الأدوات',
    'Start here: secure access, set budgets, automate plans, then use OCR/CSV.':
        'ابدأ من هنا: أمّن الوصول، اضبط الميزانيات، فعّل الخطط التلقائية ثم استخدم OCR/CSV.',
    'Budgets: {count}': 'الميزانيات: {count}',
    'Plans: {count}': 'الخطط: {count}',
    'Unread: {count}': 'غير المقروء: {count}',
    'Budget Goals + Alerts': 'أهداف الميزانية والتنبيهات',
    'Set limits and get alerts at 80% and 100%.':
        'حدد الحدود وتلق التنبيهات عند 80% و100%.',
    'Example: Food budget 300. Alert appears near 240.':
        'مثال: ميزانية الأكل 300، يظهر التنبيه قرب 240.',
    'Create one-time or recurring expenses.':
        'أنشئ مصروفات مرة واحدة أو متكررة.',
    'Example: Rent 500 on day 5 every month.':
        'مثال: إيجار 500 في اليوم 5 من كل شهر.',
    'The app works offline with local storage.':
        'التطبيق يعمل دون إنترنت مع التخزين المحلي.',
    'Example: add transactions without internet.':
        'مثال: أضف المعاملات بدون إنترنت.',
    'Monitor runtime issues and verify reporting.':
        'راقب أخطاء التشغيل وتحقق من التقارير.',
    'Example: send one test error after release.':
        'مثال: أرسل خطأ اختبار بعد الإطلاق.',
    'Track usage and refresh live thresholds.':
        'تتبع الاستخدام وحدّث الحدود المباشرة.',
    'Example: tap Refresh Config to load latest limits.':
        'مثال: اضغط تحديث الإعدادات لتحميل أحدث الحدود.',
    'Protect tools using fingerprint or PIN.':
        'احم الأدوات بالبصمة أو رمز PIN.',
    'Example: enable biometric and set a 4-digit PIN.':
        'مثال: فعّل البصمة وحدد رمز PIN من 4 أرقام.',
    'Scan receipts and convert them to expenses.':
        'امسح الإيصالات وحولها إلى مصروفات.',
    'Example: scan restaurant ticket then confirm amount.':
        'مثال: امسح فاتورة مطعم ثم أكد المبلغ.',
    'Import or export transactions with spreadsheet format.':
        'استورد أو صدّر المعاملات بصيغة الجداول.',
    'Example: export monthly report or import CSV file.':
        'مثال: صدّر تقرير الشهر أو استورد ملف CSV.',
  },
  'es': <String, String>{
    'Accounts, transfer, custom categories':
        'Cuentas, transferencias, categorías personalizadas',
    'Add Budget': 'Agregar presupuesto',
    'Add Budget Goal': 'Agregar objetivo de presupuesto',
    'Add Plan': 'Agregar plan',
    'Add Planned Payment': 'Agregar pago planificado',
    'Analytics event sent.': 'Evento de análisis enviado.',
    'Backup failed: {error}': 'Error en la copia de seguridad: {error}',
    'Billing is disabled in offline mode.':
        'La facturación está deshabilitada en modo fuera de línea.',
    'Biometric authentication failed.': 'Error de autenticación biométrica.',
    'Biometric is not supported on this device.':
        'La biometría no es compatible con este dispositivo.',
    'Biometric Lock': 'Cerradura biométrica',
    'Budget check completed.': 'Verificación de presupuesto completada.',
    'Cadence': 'Cadencia',
    'Capture runtime errors and improve app reliability.':
        'Capture errores de tiempo de ejecución y mejore la confiabilidad de la aplicación.',
    'Check Alerts': 'Verificar alertas',
    'Choose the language used across the app':
        'Elija el idioma utilizado en la aplicación',
    'Cloud sync and online login are disabled. The app now works fully offline with local storage.':
        'La sincronización en la nube y el inicio de sesión en línea están deshabilitados. La aplicación ahora funciona completamente sin conexión con almacenamiento local.',
    'Crash test logged.': 'Prueba de choque registrada.',
    'Crashlytics not configured yet. Add google-services.json and rebuild Android.':
        'Crashlytics aún no configurado. Agregue google-services.json y reconstruya Android.',
    'Create one-time or recurring plans (monthly, weekly, yearly) and process them when due.':
        'Cree planes únicos o recurrentes (mensuales, semanales, anuales) y procéselos cuando correspondan.',
    'CSV export failed.': 'Error al exportar CSV.',
    'CSV exported.': 'CSV exportado.',
    'Custom Range': 'Rango personalizado',
    'Disable PIN': 'Desactivar PIN',
    'Due date': 'Fecha de vencimiento',
    'Excel export failed: {error}': 'Exportación de Excel fallida: {error}',
    'Expense added from OCR.': 'Gasto agregado desde OCR.',
    'Export CSV': 'Exportar CSV',
    'Global (All Categories)': 'Global (todas las categorías)',
    'Global Budget': 'Presupuesto global',
    'Google Sheets export failed: {error}':
        'Error al exportar Google Sheets: {error}',
    'Import CSV': 'Importar CSV',
    'Invalid OCR amount.': 'Cantidad de OCR no válida.',
    'Invalid PIN.': 'PIN no válido.',
    'Local Database': 'Base de datos local',
    'Lock Now': 'Bloquear ahora',
    'Mark all read': 'Marcar todo como leído',
    'Monday': 'Lunes',
    'Month': 'Mes',
    'Monthly Limit': 'Límite mensual',
    'No budgets set yet.': 'Aún no hay presupuestos establecidos.',
    'No end date': 'Sin fecha de finalización',
    'No planned payments yet.': 'Aún no hay pagos planificados.',
    'Notifications': 'Notificaciones',
    'OCR failed or canceled.': 'OCR fallido o cancelado.',
    'OCR Result': 'Resultado de OCR',
    'Offline First': 'Sin conexión Primer',
    'PDF export failed: {error}': 'Error en la exportación de PDF: {error}',
    'PIN': 'PIN',
    'PIN disabled.': 'PIN deshabilitado.',
    'PIN enabled.': 'PIN habilitado.',
    'PIN must be at least 4 digits.': 'El PIN debe tener al menos 4 dígitos.',
    'Premium expense manager.\nVersion 1.0.0':
        'Administrador de gastos Premium.\nVersión 1.0.0',
    'Pro Lifetime - {price}': 'Pro Lifetime - {price}',
    'Process Now': 'Procesar ahora',
    'Refresh Config': 'Actualizar configuración',
    'Remote config refreshed.': 'Configuración remota actualizada.',
    'Remove ads': 'Eliminar anuncios',
    'Restore failed: {error}': 'Error al restaurar: {error}',
    'Save PIN': 'Guardar PIN',
    'Savings target': 'Objetivo de ahorro',
    'Scan Camera': 'Escanear cámara',
    'Scan Gallery': 'Explorar galería',
    'Security Lock Enabled': 'Bloqueo de seguridad habilitado',
    'Send Event': 'Enviar evento',
    'Send Test Error': 'Enviar error de prueba',
    'Set PIN (4-6 digits)': 'Establecer PIN (4-6 dígitos)',
    'Smart Tools Center': 'Centro de herramientas inteligentes',
    'SMART User': 'Usuario SMART',
    'Spent': 'Gastado',
    'Sunday': 'Domingo',
    'Switch Wallet': 'Switch Wallet',
    'This app is no longer maintained since November 5, 2024.\n\nYou can continue using it, but it will no longer receive updates or bug fixes. Some features may stop working over time.\n\nRecommendations:\n- Back up your data regularly.\n- Consider an actively maintained alternative.':
        'Esta aplicación ya no recibe mantenimiento desde el 5 de noviembre de 2024.\n\nPuedes seguir usándola, pero ya no recibirá actualizaciones ni correcciones de errores. Algunas funciones pueden dejar de funcionar con el tiempo.\n\nRecomendaciones:\n- Haga una copia de seguridad de sus datos periódicamente.\n- Considere una alternativa mantenida activamente.',
    'Tools': 'Herramientas',
    'Transferred {amount} {currency} between accounts.':
        'Transferido {amount} {currency} entre cuentas.',
    'Unavailable': 'No disponible',
    'Unlimited bank accounts (more than 2 wallets)':
        'Cuentas bancarias ilimitadas (más de 2 billeteras)',
    'Unlock with Biometrics': 'Desbloqueo con datos biométricos',
    'Unlock with biometrics or PIN to access tools.':
        'Desbloqueo con datos biométricos o PIN para acceder a herramientas.',
    'Unlock with PIN': 'Desbloqueo con PIN',
    'Upgrade to Pro to unlock OCR receipt scanner.':
        'Actualice a Pro para desbloquear el escáner de recibos OCR.',
    'Use fingerprint/face to protect tools.':
        'Utilice huella digital/rostro para proteger las herramientas.',
    'Week': 'Semana',
    'Usage Reached {percent}%': 'Uso alcanzado {percent}%',
    '{count} recurring expense(s) added automatically.':
        '{count} gastos recurrentes agregados automáticamente.',
    'Budget added for {category}.': 'Presupuesto agregado para {category}.',
    'Spent {amount} this month.': 'Pasé {amount} este mes.',
    'You used {spent} of {limit} spendable budget.':
        'Usó {spent} de {limit} presupuesto para gastar.',
    '{category} planned as {cadence} schedule.':
        '{category} planificado como cronograma {cadence}.',
    '{target} reached {percent}%': '{target} alcanzó el {percent}%',
    '{count} expense(s) synced to cloud.':
        '{count} gastos sincronizados con la nube.',
    '{count} expense(s) loaded from CSV.': '{count} gastos cargados desde CSV.',
    '{count} new expense(s) merged from cloud.':
        '{count} nuevos gastos fusionados desde la nube.',
  },
  'de': <String, String>{
    'Accounts, transfer, custom categories':
        'Konten, Übertragung, benutzerdefinierte Kategorien',
    'Add Budget': 'Budget hinzufügen',
    'Add Budget Goal': 'Budgetziel hinzufügen',
    'Add Plan': 'Plan hinzufügen',
    'Add Planned Payment': 'Geplante Zahlung hinzufügen',
    'Analytics event sent.': 'Analyseereignis gesendet.',
    'Backup failed: {error}': 'Sicherung fehlgeschlagen: {error}',
    'Billing is disabled in offline mode.':
        'Abrechnung ist im Offline-Modus deaktiviert.',
    'Biometric authentication failed.':
        'Biometrische Authentifizierung fehlgeschlagen.',
    'Biometric is not supported on this device.':
        'Biometrie wird auf diesem Gerät nicht unterstützt.',
    'Biometric Lock': 'Biometrische Sperre',
    'Budget check completed.': 'Budgetprüfung abgeschlossen.',
    'Cadence': 'Trittfrequenz',
    'Capture runtime errors and improve app reliability.':
        'Erfassen Sie Laufzeitfehler und verbessern Sie die App-Zuverlässigkeit.',
    'Check Alerts': 'Warnmeldungen prüfen',
    'Choose the language used across the app':
        'Wählen Sie die in der App verwendete Sprache.',
    'Cloud sync and online login are disabled. The app now works fully offline with local storage.':
        'Cloud-Synchronisierung und Online-Anmeldung sind deaktiviert. Die App funktioniert jetzt vollständig offline mit lokalem Speicher.',
    'Crash test logged.': 'Crashtest protokolliert.',
    'Crashlytics not configured yet. Add google-services.json and rebuild Android.':
        'Crashlytics noch nicht konfiguriert. Fügen Sie google-services.json hinzu und erstellen Sie Android neu.',
    'Create one-time or recurring plans (monthly, weekly, yearly) and process them when due.':
        'Erstellen Sie einmalige oder wiederkehrende Pläne (monatlich, wöchentlich, jährlich) und verarbeiten Sie diese bei Fälligkeit.',
    'CSV export failed.': 'CSV-Export fehlgeschlagen.',
    'CSV exported.': 'CSV exportiert.',
    'Custom Range': 'Benutzerdefinierter Bereich',
    'Disable PIN': 'PIN deaktivieren',
    'Due date': 'Fälligkeitsdatum',
    'Excel export failed: {error}': 'Excel-Export fehlgeschlagen: {error}',
    'Expense added from OCR.': 'Spesen aus OCR hinzugefügt.',
    'Export CSV': 'CSV exportieren',
    'Global (All Categories)': 'Global (Alle Kategorien)',
    'Global Budget': 'Globales Budget',
    'Google Sheets export failed: {error}':
        'Der Export von Google Sheets ist fehlgeschlagen: {error}',
    'Import CSV': 'CSV importieren',
    'Invalid OCR amount.': 'Ungültiger OCR-Betrag.',
    'Invalid PIN.': 'Ungültige PIN.',
    'Local Database': 'Lokale Datenbank',
    'Lock Now': 'Jetzt sperren',
    'Mark all read': 'Alles als gelesen markieren',
    'Monday': 'Montag',
    'Month': 'Monat',
    'Monthly Limit': 'Monatslimit',
    'No budgets set yet.': 'Noch keine Budgets festgelegt.',
    'No end date': 'Kein Enddatum',
    'No planned payments yet.': 'Noch keine geplanten Zahlungen.',
    'Notifications': 'Benachrichtigungen',
    'OCR failed or canceled.': 'OCR fehlgeschlagen oder abgebrochen.',
    'OCR Result': 'OCR-Ergebnis',
    'Offline First': 'Offline First',
    'PDF export failed: {error}': 'PDF-Export fehlgeschlagen: {error}',
    'PIN': 'PIN',
    'PIN disabled.': 'PIN deaktiviert.',
    'PIN enabled.': 'PIN aktiviert.',
    'PIN must be at least 4 digits.': 'PIN muss mindestens 4-stellig sein.',
    'Premium expense manager.\nVersion 1.0.0':
        'Premium-Kostenmanager.\nVersion 1.0.0',
    'Pro Lifetime - {price}': 'Pro Lifetime – {price}',
    'Process Now': 'Jetzt verarbeiten',
    'Refresh Config': 'Konfiguration aktualisieren',
    'Remote config refreshed.': 'Remote-Konfiguration aktualisiert.',
    'Remove ads': 'Werbung entfernen',
    'Restore failed: {error}': 'Wiederherstellung fehlgeschlagen: {error}',
    'Save PIN': 'PIN speichern',
    'Savings target': 'Sparziel',
    'Scan Camera': 'Kamera scannen',
    'Scan Gallery': 'Galerie scannen',
    'Security Lock Enabled': 'Sicherheitssperre aktiviert',
    'Send Event': 'Ereignis senden',
    'Send Test Error': 'Testfehler senden',
    'Set PIN (4-6 digits)': 'PIN festlegen (4-6 Ziffern)',
    'Smart Tools Center': 'Smart Tools Center',
    'SMART User': 'SMART-Benutzer',
    'Spent': 'Ausgegeben',
    'Sunday': 'Sonntag',
    'Switch Wallet': 'Geldbörse wechseln',
    'This app is no longer maintained since November 5, 2024.\n\nYou can continue using it, but it will no longer receive updates or bug fixes. Some features may stop working over time.\n\nRecommendations:\n- Back up your data regularly.\n- Consider an actively maintained alternative.':
        'Diese App wird seit dem 5. November 2024 nicht mehr gepflegt.\n\nSie können sie weiterhin verwenden, sie erhält jedoch keine Updates oder Fehlerbehebungen mehr. Einige Funktionen funktionieren möglicherweise mit der Zeit nicht mehr.\n\nEmpfehlungen:\n- Sichern Sie Ihre Daten regelmäßig.\n- Ziehen Sie eine aktiv gewartete Alternative in Betracht.',
    'Tools': 'Werkzeuge',
    'Transferred {amount} {currency} between accounts.':
        '{amount} {currency} zwischen Konten übertragen.',
    'Unavailable': 'Nicht verfügbar',
    'Unlimited bank accounts (more than 2 wallets)':
        'Unbegrenzte Bankkonten (mehr als 2 Wallets)',
    'Unlock with Biometrics': 'Mit Biometrie entsperren',
    'Unlock with biometrics or PIN to access tools.':
        'Mit Biometrie oder PIN entsperren, um auf Tools zuzugreifen.',
    'Unlock with PIN': 'Entsperren mit PIN',
    'Upgrade to Pro to unlock OCR receipt scanner.':
        'Upgrade auf Pro, um den OCR-Belegscanner zu entsperren.',
    'Use fingerprint/face to protect tools.':
        'Verwenden Sie Fingerabdruck/Gesicht, um Werkzeuge zu schützen.',
    'Week': 'Woche',
    'Usage Reached {percent}%': 'Nutzung erreicht {percent} %',
    '{count} recurring expense(s) added automatically.':
        '{count} wiederkehrende Ausgaben werden automatisch hinzugefügt.',
    'Budget added for {category}.': 'Budget für {category} hinzugefügt.',
    'Spent {amount} this month.': 'Habe diesen Monat {amount} ausgegeben.',
    'You used {spent} of {limit} spendable budget.':
        'Sie haben {spent} von {limit} auszugebendem Budget verwendet.',
    '{category} planned as {cadence} schedule.':
        '{category} geplant als {cadence} Zeitplan.',
    '{target} reached {percent}%': '{target} hat {percent} % erreicht',
    '{count} expense(s) synced to cloud.':
        '{count} Ausgaben wurden mit der Cloud synchronisiert.',
    '{count} expense(s) loaded from CSV.': '{count} Ausgaben aus CSV geladen.',
    '{count} new expense(s) merged from cloud.':
        '{count} neue Ausgaben aus der Cloud zusammengeführt.',
  },
  'it': <String, String>{
    'Accounts, transfer, custom categories':
        'Account, trasferimenti, categorie personalizzate',
    'Add Budget': 'Aggiungi budget',
    'Add Budget Goal': 'Aggiungi obiettivo budget',
    'Add Plan': 'Aggiungi piano',
    'Add Planned Payment': 'Aggiungi pagamento pianificato',
    'Analytics event sent.': 'Evento di analisi inviato.',
    'Backup failed: {error}': 'Backup non riuscito: {error}',
    'Billing is disabled in offline mode.':
        'La fatturazione è disabilitata in modalità offline.',
    'Biometric authentication failed.': 'Autenticazione biometrica fallita.',
    'Biometric is not supported on this device.':
        'La biometria non è supportata su questo dispositivo.',
    'Biometric Lock': 'Blocco biometrico',
    'Budget check completed.': 'Controllo del budget completato.',
    'Cadence': 'Cadenza',
    'Capture runtime errors and improve app reliability.':
        'Cattura gli errori di runtime e migliora l\'affidabilità dell\'app.',
    'Check Alerts': 'Controlla gli avvisi',
    'Choose the language used across the app':
        'Scegli la lingua utilizzata nell\'app',
    'Cloud sync and online login are disabled. The app now works fully offline with local storage.':
        'La sincronizzazione cloud e l\'accesso online sono disabilitati. L\'app ora funziona completamente offline con archiviazione locale.',
    'Crash test logged.': 'Crash test registrato.',
    'Crashlytics not configured yet. Add google-services.json and rebuild Android.':
        'Crashlytics non ancora configurato. Aggiungi google-services.json e ricostruisci Android.',
    'Create one-time or recurring plans (monthly, weekly, yearly) and process them when due.':
        'Crea piani una tantum o ricorrenti (mensili, settimanali, annuali) ed elaborali alla scadenza.',
    'CSV export failed.': 'Esportazione CSV non riuscita.',
    'CSV exported.': 'CSV esportato.',
    'Custom Range': 'Intervallo personalizzato',
    'Disable PIN': 'Disattiva PIN',
    'Due date': 'Data di scadenza',
    'Excel export failed: {error}': 'Esportazione Excel non riuscita: {error}',
    'Expense added from OCR.': 'Spesa aggiunta da OCR.',
    'Export CSV': 'Esporta CSV',
    'Global (All Categories)': 'Globale (tutte le categorie)',
    'Global Budget': 'Budget globale',
    'Google Sheets export failed: {error}':
        'Esportazione di Fogli Google non riuscita: {error}',
    'Import CSV': 'Importa CSV',
    'Invalid OCR amount.': 'Importo OCR non valido.',
    'Invalid PIN.': 'PIN non valido.',
    'Local Database': 'Database locale',
    'Lock Now': 'Blocca ora',
    'Mark all read': 'Segna tutto letto',
    'Monday': 'Lunedì',
    'Month': 'Mese',
    'Monthly Limit': 'Limite mensile',
    'No budgets set yet.': 'Nessun budget ancora impostato.',
    'No end date': 'Nessuna data di fine',
    'No planned payments yet.': 'Ancora nessun pagamento pianificato.',
    'Notifications': 'Notifiche',
    'OCR failed or canceled.': 'OCR non riuscito o annullato.',
    'OCR Result': 'Risultato OCR',
    'Offline First': 'Offline Prima',
    'PDF export failed: {error}': 'Esportazione PDF non riuscita: {error}',
    'PIN': 'PIN',
    'PIN disabled.': 'PIN disabilitato.',
    'PIN enabled.': 'PIN attivato.',
    'PIN must be at least 4 digits.': 'Il PIN deve contenere almeno 4 cifre.',
    'Premium expense manager.\nVersion 1.0.0':
        'Gestore spese Premium.\nVersione 1.0.0',
    'Pro Lifetime - {price}': 'Pro Lifetime - {price}',
    'Process Now': 'Elabora ora',
    'Refresh Config': 'Aggiorna configurazione',
    'Remote config refreshed.': 'Configurazione remota aggiornata.',
    'Remove ads': 'Rimuovi annunci',
    'Restore failed: {error}': 'Ripristino fallito: {error}',
    'Save PIN': 'Salva PIN',
    'Savings target': 'Destinazione di risparmio',
    'Scan Camera': 'Scansione fotocamera',
    'Scan Gallery': 'Scansione galleria',
    'Security Lock Enabled': 'Blocco di sicurezza abilitato',
    'Send Event': 'Invia evento',
    'Send Test Error': 'Errore test invio',
    'Set PIN (4-6 digits)': 'Imposta PIN (4-6 cifre)',
    'Smart Tools Center': 'Centro strumenti Smart',
    'SMART User': 'Utente SMART',
    'Spent': 'Spesa',
    'Sunday': 'Domenica',
    'Switch Wallet': 'Cambia portafoglio',
    'This app is no longer maintained since November 5, 2024.\n\nYou can continue using it, but it will no longer receive updates or bug fixes. Some features may stop working over time.\n\nRecommendations:\n- Back up your data regularly.\n- Consider an actively maintained alternative.':
        'Questa app non viene più gestita dal 5 novembre 2024.\n\nPuoi continuare a utilizzarla, ma non riceverà più aggiornamenti o correzioni di bug. Alcune funzionalità potrebbero smettere di funzionare nel tempo.\n\nConsigli:\n- Effettua regolarmente il backup dei tuoi dati.\n- Considera un\'alternativa mantenuta attivamente.',
    'Tools': 'Strumenti',
    'Transferred {amount} {currency} between accounts.':
        'Trasferito {amount} {currency} tra account.',
    'Unavailable': 'Non disponibile',
    'Unlimited bank accounts (more than 2 wallets)':
        'Conti bancari illimitati (più di 2 portafogli)',
    'Unlock with Biometrics': 'Sblocca con la biometria',
    'Unlock with biometrics or PIN to access tools.':
        'Sblocca con la biometria o il PIN per accedere agli strumenti.',
    'Unlock with PIN': 'Sblocca con PIN',
    'Upgrade to Pro to unlock OCR receipt scanner.':
        'Passa a Pro per sbloccare lo scanner di ricevute OCR.',
    'Use fingerprint/face to protect tools.':
        'Utilizza l\'impronta digitale/il volto per proteggere gli strumenti.',
    'Week': 'Settimana',
    'Usage Reached {percent}%': 'Utilizzo raggiunto {percent}%',
    '{count} recurring expense(s) added automatically.':
        '{count} spese ricorrenti aggiunte automaticamente.',
    'Budget added for {category}.': 'Budget aggiunto per {category}.',
    'Spent {amount} this month.': 'Ho speso {amount} questo mese.',
    'You used {spent} of {limit} spendable budget.':
        'Hai utilizzato {spent} del {limit} budget spendibile.',
    '{category} planned as {cadence} schedule.':
        '{category} pianificato come programma {cadence}.',
    '{target} reached {percent}%': '{target} ha raggiunto il {percent}%',
    '{count} expense(s) synced to cloud.':
        'Spese {count} sincronizzate sul cloud.',
    '{count} expense(s) loaded from CSV.': '{count} spesa/e caricata/e da CSV.',
    '{count} new expense(s) merged from cloud.':
        '{count} nuove spese unite dal cloud.',
  },
  'pt': <String, String>{
    'Accounts, transfer, custom categories':
        'Contas, transferência, categorias personalizadas',
    'Add Budget': 'Adicionar orçamento',
    'Add Budget Goal': 'Adicionar meta de orçamento',
    'Add Plan': 'Adicionar plano',
    'Add Planned Payment': 'Adicionar pagamento planejado',
    'Analytics event sent.': 'Evento de análise enviado.',
    'Backup failed: {error}': 'Falha no backup: {error}',
    'Billing is disabled in offline mode.':
        'A cobrança está desativada no modo offline.',
    'Biometric authentication failed.': 'Falha na autenticação biométrica.',
    'Biometric is not supported on this device.':
        'A biometria não é compatível com este dispositivo.',
    'Biometric Lock': 'Bloqueio Biométrico',
    'Budget check completed.': 'Verificação de orçamento concluída.',
    'Cadence': 'Cadência',
    'Capture runtime errors and improve app reliability.':
        'Capture erros de tempo de execução e melhore a confiabilidade do aplicativo.',
    'Check Alerts': 'Verificar alertas',
    'Choose the language used across the app':
        'Escolha o idioma usado no aplicativo',
    'Cloud sync and online login are disabled. The app now works fully offline with local storage.':
        'A sincronização na nuvem e o login online estão desativados. O aplicativo agora funciona totalmente offline com armazenamento local.',
    'Crash test logged.': 'Teste de falha registrado.',
    'Crashlytics not configured yet. Add google-services.json and rebuild Android.':
        'Crashlytics ainda não configurado. Adicione google-services.json e reconstrua o Android.',
    'Create one-time or recurring plans (monthly, weekly, yearly) and process them when due.':
        'Crie planos únicos ou recorrentes (mensais, semanais, anuais) e processe-os no vencimento.',
    'CSV export failed.': 'Falha na exportação de CSV.',
    'CSV exported.': 'CSV exportado.',
    'Custom Range': 'Intervalo personalizado',
    'Disable PIN': 'Desativar PIN',
    'Due date': 'Data de vencimento',
    'Excel export failed: {error}': 'Falha na exportação do Excel: {error}',
    'Expense added from OCR.': 'Despesa adicionada do OCR.',
    'Export CSV': 'Exportar CSV',
    'Global (All Categories)': 'Global (todas as categorias)',
    'Global Budget': 'Orçamento global',
    'Google Sheets export failed: {error}':
        'Falha na exportação do Planilhas Google: {error}',
    'Import CSV': 'Importar CSV',
    'Invalid OCR amount.': 'Quantidade de OCR inválida.',
    'Invalid PIN.': 'PIN inválido.',
    'Local Database': 'Banco de dados local',
    'Lock Now': 'Bloquear agora',
    'Mark all read': 'Marcar tudo como lido',
    'Monday': 'Segunda-feira',
    'Month': 'Mês',
    'Monthly Limit': 'Limite mensal',
    'No budgets set yet.': 'Nenhum orçamento definido ainda.',
    'No end date': 'Sem data de término',
    'No planned payments yet.': 'Nenhum pagamento planejado ainda.',
    'Notifications': 'Notificações',
    'OCR failed or canceled.': 'OCR falhou ou foi cancelado.',
    'OCR Result': 'Resultado OCR',
    'Offline First': 'Off-line Primeiro',
    'PDF export failed: {error}': 'Falha na exportação de PDF: {error}',
    'PIN': 'PIN',
    'PIN disabled.': 'PIN desativado.',
    'PIN enabled.': 'PIN ativado.',
    'PIN must be at least 4 digits.': 'O PIN deve ter pelo menos 4 dígitos.',
    'Premium expense manager.\nVersion 1.0.0':
        'Gerenciador de despesas premium.\nVersão 1.0.0',
    'Pro Lifetime - {price}': 'Pro Lifetime - {price}',
    'Process Now': 'Processar agora',
    'Refresh Config': 'Atualizar configuração',
    'Remote config refreshed.': 'Configuração remota atualizada.',
    'Remove ads': 'Remover anúncios',
    'Restore failed: {error}': 'Falha na restauração: {error}',
    'Save PIN': 'Salvar PIN',
    'Savings target': 'Meta de economia',
    'Scan Camera': 'Digitalizar câmera',
    'Scan Gallery': 'Digitalizar galeria',
    'Security Lock Enabled': 'Bloqueio de segurança ativado',
    'Send Event': 'Enviar evento',
    'Send Test Error': 'Enviar erro de teste',
    'Set PIN (4-6 digits)': 'Definir PIN (4-6 dígitos)',
    'Smart Tools Center': 'Centro de ferramentas inteligentes',
    'SMART User': 'Usuário SMART',
    'Spent': 'Gasto',
    'Sunday': 'Domingo',
    'Switch Wallet': 'Trocar de carteira',
    'This app is no longer maintained since November 5, 2024.\n\nYou can continue using it, but it will no longer receive updates or bug fixes. Some features may stop working over time.\n\nRecommendations:\n- Back up your data regularly.\n- Consider an actively maintained alternative.':
        'Este aplicativo não é mais mantido desde 5 de novembro de 2024.\n\nVocê pode continuar usando-o, mas ele não receberá mais atualizações ou correções de bugs. Alguns recursos podem parar de funcionar com o tempo.\n\nRecomendações:\n- Faça backup dos seus dados regularmente.\n- Considere uma alternativa com manutenção ativa.',
    'Tools': 'Ferramentas',
    'Transferred {amount} {currency} between accounts.':
        'Transferido {amount} {currency} entre contas.',
    'Unavailable': 'Indisponível',
    'Unlimited bank accounts (more than 2 wallets)':
        'Contas bancárias ilimitadas (mais de 2 carteiras)',
    'Unlock with Biometrics': 'Desbloqueio com Biometria',
    'Unlock with biometrics or PIN to access tools.':
        'Desbloqueio com biometria ou PIN para acesso às ferramentas.',
    'Unlock with PIN': 'Desbloqueio com PIN',
    'Upgrade to Pro to unlock OCR receipt scanner.':
        'Atualize para Pro para desbloquear o scanner de recibos OCR.',
    'Use fingerprint/face to protect tools.':
        'Use impressão digital/face para proteger ferramentas.',
    'Week': 'Semana',
    'Usage Reached {percent}%': 'Uso alcançado {percent}%',
    '{count} recurring expense(s) added automatically.':
        '{count} despesas recorrentes adicionadas automaticamente.',
    'Budget added for {category}.': 'Orçamento adicionado para {category}.',
    'Spent {amount} this month.': 'Gastei {amount} este mês.',
    'You used {spent} of {limit} spendable budget.':
        'Você usou {spent} de {limit} orçamento disponível.',
    '{category} planned as {cadence} schedule.':
        '{category} planejado como cronograma {cadence}.',
    '{target} reached {percent}%': '{target} atingiu {percent}%',
    '{count} expense(s) synced to cloud.':
        '{count} despesas sincronizadas com a nuvem.',
    '{count} expense(s) loaded from CSV.':
        '{count} despesas carregadas do CSV.',
    '{count} new expense(s) merged from cloud.':
        '{count} novas despesas mescladas da nuvem.',
  },
  'ru': <String, String>{
    'Accounts, transfer, custom categories':
        'Счета, перевод, пользовательские категории',
    'Add Budget': 'Добавить бюджет',
    'Add Budget Goal': 'Добавить цель бюджета',
    'Add Plan': 'Добавить план',
    'Add Planned Payment': 'Добавить запланированный платеж',
    'Analytics event sent.': 'Аналитическое событие отправлено.',
    'Backup failed: {error}':
        'Не удалось выполнить резервное копирование: {error}',
    'Billing is disabled in offline mode.':
        'Выставление счетов отключено в автономном режиме.',
    'Biometric authentication failed.':
        'Биометрическая аутентификация не удалась.',
    'Biometric is not supported on this device.':
        'Биометрические данные не поддерживаются на этом устройстве.',
    'Biometric Lock': 'Биометрическая блокировка',
    'Budget check completed.': 'Проверка бюджета завершена.',
    'Cadence': 'Каденция',
    'Capture runtime errors and improve app reliability.':
        'Фиксируйте ошибки времени выполнения и повышайте надежность приложения.',
    'Check Alerts': 'Проверить оповещения',
    'Choose the language used across the app':
        'Выберите язык, используемый в приложении',
    'Cloud sync and online login are disabled. The app now works fully offline with local storage.':
        'Облачная синхронизация и онлайн-вход отключены. Приложение теперь работает полностью в автономном режиме с локальным хранилищем.',
    'Crash test logged.': 'Записан краш-тест.',
    'Crashlytics not configured yet. Add google-services.json and rebuild Android.':
        'Crashlytics еще не настроен. Добавьте google-services.json и пересоберите Android.',
    'Create one-time or recurring plans (monthly, weekly, yearly) and process them when due.':
        'Создавайте разовые или повторяющиеся планы (ежемесячно, еженедельно, ежегодно) и обрабатывайте их в установленные сроки.',
    'CSV export failed.': 'Не удалось экспортировать CSV.',
    'CSV exported.': 'CSV экспортирован.',
    'Custom Range': 'Пользовательский диапазон',
    'Disable PIN': 'Отключить PIN',
    'Due date': 'Срок оплаты',
    'Excel export failed: {error}':
        'Не удалось экспортировать в Excel: {error}',
    'Expense added from OCR.': 'Расходы добавлены из OCR.',
    'Export CSV': 'Экспорт в CSV',
    'Global (All Categories)': 'Глобальный (все категории)',
    'Global Budget': 'Глобальный бюджет',
    'Google Sheets export failed: {error}':
        'Не удалось экспортировать в Google Таблицы: {error}',
    'Import CSV': 'Импортировать CSV',
    'Invalid OCR amount.': 'Недопустимая сумма OCR.',
    'Invalid PIN.': 'Неверный PIN-код.',
    'Local Database': 'Локальная база данных',
    'Lock Now': 'Заблокировать сейчас',
    'Mark all read': 'Отметить все прочитанными',
    'Monday': 'Понедельник',
    'Month': 'Месяц',
    'Monthly Limit': 'Ежемесячный лимит',
    'No budgets set yet.': 'Бюджеты пока не установлены.',
    'No end date': 'Нет даты окончания',
    'No planned payments yet.': 'Пока нет запланированных платежей.',
    'Notifications': 'Уведомления',
    'OCR failed or canceled.':
        'Ошибка оптического распознавания символов или оно отменено.',
    'OCR Result': 'Результат распознавания',
    'Offline First': 'Не в сети. Сначала',
    'PDF export failed: {error}': 'не удалось экспортировать PDF: {error}',
    'PIN': 'PIN',
    'PIN disabled.': 'PIN отключен.',
    'PIN enabled.': 'PIN-код включен.',
    'PIN must be at least 4 digits.':
        'PIN-код должен состоять как минимум из 4 цифр.',
    'Premium expense manager.\nVersion 1.0.0':
        'Премиум-менеджер расходов.\nВерсия 1.0.0',
    'Pro Lifetime - {price}': 'Pro Lifetime - {price}',
    'Process Now': 'Обработать сейчас',
    'Refresh Config': 'Обновить конфигурацию',
    'Remote config refreshed.': 'Удаленная конфигурация обновлена.',
    'Remove ads': 'Удалить рекламу',
    'Restore failed: {error}': 'Не удалось восстановить: {error}',
    'Save PIN': 'Сохранить PIN-код',
    'Savings target': 'Цель экономии',
    'Scan Camera': 'Сканировать камеру',
    'Scan Gallery': 'Сканировать галерею',
    'Security Lock Enabled': 'Блокировка безопасности включена',
    'Send Event': 'Отправить событие',
    'Send Test Error': 'Отправить ошибку теста',
    'Set PIN (4-6 digits)': 'Установить PIN-код (4-6 цифр)',
    'Smart Tools Center': 'Центр интеллектуальных инструментов',
    'SMART User': 'Пользователь SMART',
    'Spent': 'Потрачено',
    'Sunday': 'Воскресенье',
    'Switch Wallet': 'Switch Wallet',
    'This app is no longer maintained since November 5, 2024.\n\nYou can continue using it, but it will no longer receive updates or bug fixes. Some features may stop working over time.\n\nRecommendations:\n- Back up your data regularly.\n- Consider an actively maintained alternative.':
        'Это приложение больше не поддерживается с 5 ноября 2024 г.\n\nВы можете продолжать использовать его, но оно больше не будет получать обновления и исправления ошибок. Некоторые функции могут со временем перестать работать.\n\nРекомендации:\n- Регулярно создавайте резервные копии данных.\n- Рассмотрите активно поддерживаемую альтернативу.',
    'Tools': 'Инструменты',
    'Transferred {amount} {currency} between accounts.':
        'Перенос {amount} {currency} между учетными записями.',
    'Unavailable': 'Недоступно',
    'Unlimited bank accounts (more than 2 wallets)':
        'Неограниченное количество банковских счетов (более 2 кошельков)',
    'Unlock with Biometrics': 'Разблокировка с помощью биометрии',
    'Unlock with biometrics or PIN to access tools.':
        'Разблокировка с помощью биометрии или PIN-кода для доступа к инструментам.',
    'Unlock with PIN': 'Разблокировка с помощью PIN-кода',
    'Upgrade to Pro to unlock OCR receipt scanner.':
        'Обновите версию до Pro, чтобы разблокировать сканер квитанций OCR.',
    'Use fingerprint/face to protect tools.':
        'Используйте отпечаток пальца/лицо для защиты инструментов.',
    'Week': 'Неделя',
    'Usage Reached {percent}%': 'Использование достигло {percent}%',
    '{count} recurring expense(s) added automatically.':
        '{count} периодические расходы добавляются автоматически.',
    'Budget added for {category}.': 'Бюджет добавлен для {category}.',
    'Spent {amount} this month.': 'В этом месяце потрачено {amount}.',
    'You used {spent} of {limit} spendable budget.':
        'Вы использовали {spent} из расходуемого бюджета {limit}.',
    '{category} planned as {cadence} schedule.':
        '{category} запланировано как расписание {cadence}.',
    '{target} reached {percent}%': '{target} достиг {percent}%',
    '{count} expense(s) synced to cloud.':
        'Расходы {count} синхронизированы с облаком.',
    '{count} expense(s) loaded from CSV.': 'Расходы {count} загружены из CSV.',
    '{count} new expense(s) merged from cloud.':
        '{count} новые расходы объединены из облака.',
  },
  'tr': <String, String>{
    'Accounts, transfer, custom categories':
        'Hesaplar, aktarım, özel kategoriler',
    'Add Budget': 'Bütçe Ekle',
    'Add Budget Goal': 'Bütçe Hedefi Ekle',
    'Add Plan': 'Plan Ekle',
    'Add Planned Payment': 'Planlanan Ödemeyi Ekle',
    'Analytics event sent.': 'Analytics etkinliği gönderildi.',
    'Backup failed: {error}': 'Yedekleme başarısız oldu: {error}',
    'Billing is disabled in offline mode.':
        'Faturalandırma çevrimdışı modda devre dışı bırakıldı.',
    'Biometric authentication failed.':
        'Biyometrik kimlik doğrulama başarısız oldu.',
    'Biometric is not supported on this device.':
        'Biyometrik bu cihazda desteklenmiyor.',
    'Biometric Lock': 'Biyometrik Kilit',
    'Budget check completed.': 'Bütçe kontrolü tamamlandı.',
    'Cadence': 'Tempo',
    'Capture runtime errors and improve app reliability.':
        'Çalışma zamanı hatalarını yakalayın ve uygulama güvenilirliğini artırın.',
    'Check Alerts': 'Uyarıları Kontrol Et',
    'Choose the language used across the app':
        'Uygulamada kullanılan dili seçin',
    'Cloud sync and online login are disabled. The app now works fully offline with local storage.':
        'Bulut senkronizasyonu ve çevrimiçi oturum açma devre dışı bırakılır. Uygulama artık yerel depolamayla tamamen çevrimdışı çalışıyor.',
    'Crash test logged.': 'Çarpışma testi günlüğe kaydedildi.',
    'Crashlytics not configured yet. Add google-services.json and rebuild Android.':
        'Crashlytics henüz yapılandırılmadı. Google-services.json\'u ekleyin ve Android\'i yeniden oluşturun.',
    'Create one-time or recurring plans (monthly, weekly, yearly) and process them when due.':
        'Bir kerelik veya yinelenen planlar (aylık, haftalık, yıllık) oluşturun ve bunları zamanı geldiğinde işleyin.',
    'CSV export failed.': 'CSV aktarımı başarısız oldu.',
    'CSV exported.': 'CSV dışa aktarıldı.',
    'Custom Range': 'Özel Aralık',
    'Disable PIN': 'PIN\'i devre dışı bırak',
    'Due date': 'Son tarih',
    'Excel export failed: {error}': 'Excel aktarımı başarısız oldu: {error}',
    'Expense added from OCR.': 'Gider OCR\'dan eklendi.',
    'Export CSV': 'CSV\'yi Dışa Aktar',
    'Global (All Categories)': 'Küresel (Tüm Kategoriler)',
    'Global Budget': 'Genel Bütçe',
    'Google Sheets export failed: {error}':
        'Google E-Tablolar dışa aktarımı başarısız oldu: {error}',
    'Import CSV': 'CSV\'yi içe aktar',
    'Invalid OCR amount.': 'Geçersiz OCR miktarı.',
    'Invalid PIN.': 'Geçersiz PIN.',
    'Local Database': 'Yerel Veritabanı',
    'Lock Now': 'Şimdi Kilitle',
    'Mark all read': 'Tümünü okundu olarak işaretle',
    'Monday': 'Pazartesi',
    'Month': 'Ay',
    'Monthly Limit': 'Aylık Limit',
    'No budgets set yet.': 'Henüz bütçe belirlenmedi.',
    'No end date': 'Bitiş tarihi yok',
    'No planned payments yet.': 'Henüz planlanmış bir ödeme yok.',
    'Notifications': 'Bildirimler',
    'OCR failed or canceled.': 'OCR başarısız oldu veya iptal edildi.',
    'OCR Result': 'OCR Sonucu',
    'Offline First': 'Çevrimdışı İlk',
    'PDF export failed: {error}': 'PDF dışa aktarımı başarısız oldu: {error}',
    'PIN': 'PIN',
    'PIN disabled.': 'PIN devre dışı.',
    'PIN enabled.': 'PIN etkinleştirildi.',
    'PIN must be at least 4 digits.': 'PIN en az 4 haneli olmalıdır.',
    'Premium expense manager.\nVersion 1.0.0':
        'Premium gider yöneticisi.\nSürüm 1.0.0',
    'Pro Lifetime - {price}': 'Pro Ömür Boyu - {price}',
    'Process Now': 'Şimdi İşle',
    'Refresh Config': 'Yapılandırmayı Yenile',
    'Remote config refreshed.': 'Uzaktan yapılandırma yenilendi.',
    'Remove ads': 'Reklamları kaldır',
    'Restore failed: {error}': 'Geri yükleme başarısız oldu: {error}',
    'Save PIN': 'PIN\'i kaydet',
    'Savings target': 'Kayıt hedefi',
    'Scan Camera': 'Kamerayı Tara',
    'Scan Gallery': 'Galeriyi Tara',
    'Security Lock Enabled': 'Güvenlik Kilidi Etkin',
    'Send Event': 'Olayı Gönder',
    'Send Test Error': 'Test Hatası Gönder',
    'Set PIN (4-6 digits)': 'PIN Ayarla (4-6 basamak)',
    'Smart Tools Center': 'Akıllı Araçlar Merkezi',
    'SMART User': 'SMART Kullanıcısı',
    'Spent': 'Harcandı',
    'Sunday': 'Pazar',
    'Switch Wallet': 'Cüzdanı Değiştir',
    'This app is no longer maintained since November 5, 2024.\n\nYou can continue using it, but it will no longer receive updates or bug fixes. Some features may stop working over time.\n\nRecommendations:\n- Back up your data regularly.\n- Consider an actively maintained alternative.':
        'Bu uygulama 5 Kasım 2024\'ten beri artık desteklenmiyor.\n\nKullanmaya devam edebilirsiniz ancak artık güncelleme veya hata düzeltmesi almayacaktır. Bazı özellikler zamanla çalışmayı durdurabilir.\n\nÖneriler:\n- Verilerinizi düzenli olarak yedekleyin.\n- Aktif olarak bakımı yapılan bir alternatifi düşünün.',
    'Tools': 'Araçlar',
    'Transferred {amount} {currency} between accounts.':
        'Hesaplar arasında {amount} {currency} aktarıldı.',
    'Unavailable': 'Kullanılamıyor',
    'Unlimited bank accounts (more than 2 wallets)':
        'Sınırsız banka hesabı (2\'den fazla cüzdan)',
    'Unlock with Biometrics': 'Biyometri ile kilidi açın',
    'Unlock with biometrics or PIN to access tools.':
        'Araçlara erişmek için biyometri veya PIN ile kilidi açın.',
    'Unlock with PIN': 'PIN ile kilidi açın',
    'Upgrade to Pro to unlock OCR receipt scanner.':
        'OCR makbuz tarayıcısının kilidini açmak için Pro\'ya yükseltin.',
    'Use fingerprint/face to protect tools.':
        'Araçları korumak için parmak izini/yüzünü kullanın.',
    'Week': 'Hafta',
    'Usage Reached {percent}%': 'Kullanım %{percent}\'a Ulaştı',
    '{count} recurring expense(s) added automatically.':
        '{count} yinelenen gider(ler) otomatik olarak eklenir.',
    'Budget added for {category}.': '{category} için bütçe eklendi.',
    'Spent {amount} this month.': 'Bu ay {amount} harcadım.',
    'You used {spent} of {limit} spendable budget.':
        '{limit} harcanabilir bütçenin {spent} kadarını kullandınız.',
    '{category} planned as {cadence} schedule.':
        '{category}, {cadence} planı olarak planlandı.',
    '{target} reached {percent}%': '{target} %{percent} değerine ulaştı',
    '{count} expense(s) synced to cloud.':
        '{count} gider(ler) bulutla senkronize edildi.',
    '{count} expense(s) loaded from CSV.':
        '{count} gider(ler) CSV\'den yüklendi.',
    '{count} new expense(s) merged from cloud.':
        '{count} yeni gider(ler) buluttan birleştirildi.',
  },
  'id': <String, String>{
    'Accounts, transfer, custom categories': 'Akun, transfer, kategori khusus',
    'Add Budget': 'Tambahkan Anggaran',
    'Add Budget Goal': 'Tambahkan Sasaran Anggaran',
    'Add Plan': 'Tambahkan Paket',
    'Add Planned Payment': 'Tambahkan Pembayaran Terencana',
    'Analytics event sent.': 'Peristiwa analitik terkirim.',
    'Backup failed: {error}': 'Pencadangan gagal: {error}',
    'Billing is disabled in offline mode.':
        'Penagihan dinonaktifkan dalam mode offline.',
    'Biometric authentication failed.': 'Otentikasi biometrik gagal.',
    'Biometric is not supported on this device.':
        'Biometrik tidak didukung pada perangkat ini.',
    'Biometric Lock': 'Kunci Biometrik',
    'Budget check completed.': 'Pemeriksaan anggaran selesai.',
    'Cadence': 'Irama',
    'Capture runtime errors and improve app reliability.':
        'Menangkap error runtime dan meningkatkan keandalan aplikasi.',
    'Check Alerts': 'Periksa Peringatan',
    'Choose the language used across the app':
        'Pilih bahasa yang digunakan di seluruh aplikasi',
    'Cloud sync and online login are disabled. The app now works fully offline with local storage.':
        'Sinkronisasi cloud dan login online dinonaktifkan. Aplikasi ini sekarang berfungsi sepenuhnya offline dengan penyimpanan lokal.',
    'Crash test logged.': 'Uji kerusakan dicatat.',
    'Crashlytics not configured yet. Add google-services.json and rebuild Android.':
        'Crashlytics belum dikonfigurasi. Tambahkan google-services.json dan bangun kembali Android.',
    'Create one-time or recurring plans (monthly, weekly, yearly) and process them when due.':
        'Buat rencana satu kali atau berulang (bulanan, mingguan, tahunan) dan proses saat jatuh tempo.',
    'CSV export failed.': 'Ekspor CSV gagal.',
    'CSV exported.': 'CSV diekspor.',
    'Custom Range': 'Rentang Kustom',
    'Disable PIN': 'Nonaktifkan PIN',
    'Due date': 'Tanggal jatuh tempo',
    'Excel export failed: {error}': 'Ekspor Excel gagal: {error}',
    'Expense added from OCR.': 'Biaya ditambahkan dari OCR.',
    'Export CSV': 'Ekspor CSV',
    'Global (All Categories)': 'Global (Semua Kategori)',
    'Global Budget': 'Anggaran Global',
    'Google Sheets export failed: {error}':
        'Ekspor Google Spreadsheet gagal: {error}',
    'Import CSV': 'Impor CSV',
    'Invalid OCR amount.': 'Jumlah OCR tidak valid.',
    'Invalid PIN.': 'PIN tidak valid.',
    'Local Database': 'Basis Data Lokal',
    'Lock Now': 'Kunci Sekarang',
    'Mark all read': 'Tandai semua telah dibaca',
    'Monday': 'Senin',
    'Month': 'Bulan',
    'Monthly Limit': 'Batas Bulanan',
    'No budgets set yet.': 'Belum ada anggaran yang ditetapkan.',
    'No end date': 'Belum ada tanggal akhir',
    'No planned payments yet.': 'Belum ada rencana pembayaran.',
    'Notifications': 'Pemberitahuan',
    'OCR failed or canceled.': 'OCR gagal atau dibatalkan.',
    'OCR Result': 'Hasil OCR',
    'Offline First': 'Offline Pertama',
    'PDF export failed: {error}': 'Ekspor PDF gagal: {error}',
    'PIN': 'PIN',
    'PIN disabled.': 'PIN dinonaktifkan.',
    'PIN enabled.': 'PIN diaktifkan.',
    'PIN must be at least 4 digits.': 'PIN minimal harus 4 digit.',
    'Premium expense manager.\nVersion 1.0.0':
        'Manajer pengeluaran premium.\nVersi 1.0.0',
    'Pro Lifetime - {price}': 'Pro Seumur Hidup - {price}',
    'Process Now': 'Proses Sekarang',
    'Refresh Config': 'Segarkan Konfigurasi',
    'Remote config refreshed.': 'Konfigurasi jarak jauh disegarkan.',
    'Remove ads': 'Hapus iklan',
    'Restore failed: {error}': 'Pemulihan gagal: {error}',
    'Save PIN': 'Simpan PIN',
    'Savings target': 'Target penghematan',
    'Scan Camera': 'Pindai Kamera',
    'Scan Gallery': 'Pindai Galeri',
    'Security Lock Enabled': 'Kunci Keamanan Diaktifkan',
    'Send Event': 'Kirim Acara',
    'Send Test Error': 'Kirim Kesalahan Tes',
    'Set PIN (4-6 digits)': 'Tetapkan PIN (4-6 digit)',
    'Smart Tools Center': 'Pusat Alat Cerdas',
    'SMART User': 'Pengguna CERDAS',
    'Spent': 'Menghabiskan',
    'Sunday': 'Minggu',
    'Switch Wallet': 'Ganti Dompet',
    'This app is no longer maintained since November 5, 2024.\n\nYou can continue using it, but it will no longer receive updates or bug fixes. Some features may stop working over time.\n\nRecommendations:\n- Back up your data regularly.\n- Consider an actively maintained alternative.':
        'Aplikasi ini tidak lagi dikelola sejak 5 November 2024.\n\nAnda dapat terus menggunakannya, namun aplikasi ini tidak akan lagi menerima pembaruan atau perbaikan bug. Beberapa fitur mungkin berhenti berfungsi seiring berjalannya waktu.\n\nRekomendasi:\n- Cadangkan data Anda secara rutin.\n- Pertimbangkan alternatif yang dikelola secara aktif.',
    'Tools': 'Alat',
    'Transferred {amount} {currency} between accounts.':
        'Ditransfer {amount} {currency} antar akun.',
    'Unavailable': 'Tidak tersedia',
    'Unlimited bank accounts (more than 2 wallets)':
        'Rekening bank tidak terbatas (lebih dari 2 dompet)',
    'Unlock with Biometrics': 'Buka kunci dengan Biometrik',
    'Unlock with biometrics or PIN to access tools.':
        'Buka kunci dengan biometrik atau PIN untuk mengakses alat.',
    'Unlock with PIN': 'Buka kunci dengan PIN',
    'Upgrade to Pro to unlock OCR receipt scanner.':
        'Tingkatkan ke Pro untuk membuka kunci pemindai tanda terima OCR.',
    'Use fingerprint/face to protect tools.':
        'Gunakan sidik jari/wajah untuk melindungi alat.',
    'Week': 'Minggu',
    'Usage Reached {percent}%': 'Penggunaan Mencapai {percent}%',
    '{count} recurring expense(s) added automatically.':
        '{count} pengeluaran berulang ditambahkan secara otomatis.',
    'Budget added for {category}.': 'Anggaran ditambahkan untuk {category}.',
    'Spent {amount} this month.': 'Menghabiskan {amount} bulan ini.',
    'You used {spent} of {limit} spendable budget.':
        'Anda menggunakan {spent} dari {limit} anggaran yang dapat dibelanjakan.',
    '{category} planned as {cadence} schedule.':
        '{category} direncanakan sesuai jadwal {cadence}.',
    '{target} reached {percent}%': '{target} mencapai {percent}%',
    '{count} expense(s) synced to cloud.':
        '{count} pengeluaran disinkronkan ke cloud.',
    '{count} expense(s) loaded from CSV.':
        '{count} pengeluaran dimuat dari CSV.',
    '{count} new expense(s) merged from cloud.':
        '{count} pengeluaran baru digabungkan dari cloud.',
  },
  'hi': <String, String>{
    'Accounts, transfer, custom categories':
        'खाते, स्थानांतरण, कस्टम श्रेणियां',
    'Add Budget': 'बजट जोड़ें',
    'Add Budget Goal': 'बजट लक्ष्य जोड़ें',
    'Add Plan': 'योजना जोड़ें',
    'Add Planned Payment': 'नियोजित भुगतान जोड़ें',
    'Analytics event sent.': 'एनालिटिक्स इवेंट भेजा गया।',
    'Backup failed: {error}': 'बैकअप विफल: {error}',
    'Billing is disabled in offline mode.': 'ऑफ़लाइन मोड में बिलिंग अक्षम है।',
    'Biometric authentication failed.': 'बायोमेट्रिक प्रमाणीकरण विफल रहा।',
    'Biometric is not supported on this device.':
        'इस डिवाइस पर बायोमेट्रिक समर्थित नहीं है।',
    'Biometric Lock': 'बायोमेट्रिक लॉक',
    'Budget check completed.': 'बजट जांच पूरी हुई।',
    'Cadence': 'कैडेंस',
    'Capture runtime errors and improve app reliability.':
        'रनटाइम त्रुटियों को कैप्चर करें और ऐप की विश्वसनीयता में सुधार करें।',
    'Check Alerts': 'अलर्ट जांचें',
    'Choose the language used across the app':
        'ऐप में उपयोग की जाने वाली भाषा चुनें',
    'Cloud sync and online login are disabled. The app now works fully offline with local storage.':
        'क्लाउड सिंक और ऑनलाइन लॉगिन अक्षम हैं। ऐप अब स्थानीय स्टोरेज के साथ पूरी तरह ऑफ़लाइन काम करता है।',
    'Crash test logged.': 'क्रैश टेस्ट लॉग किया गया।',
    'Crashlytics not configured yet. Add google-services.json and rebuild Android.':
        'क्रैशलाइटिक्स अभी तक कॉन्फ़िगर नहीं किया गया है। google-services.json जोड़ें और Android का पुनर्निर्माण करें।',
    'Create one-time or recurring plans (monthly, weekly, yearly) and process them when due.':
        'एकमुश्त या आवर्ती योजनाएं (मासिक, साप्ताहिक, वार्षिक) बनाएं और नियत समय पर उन्हें संसाधित करें।',
    'CSV export failed.': 'CSV निर्यात विफल रहा.',
    'CSV exported.': 'CSV निर्यात किया गया।',
    'Custom Range': 'कस्टम रेंज',
    'Disable PIN': 'पिन अक्षम करें',
    'Due date': 'देय तिथि',
    'Excel export failed: {error}': 'एक्सेल निर्यात विफल: {error}',
    'Expense added from OCR.': 'व्यय OCR से जोड़ा गया।',
    'Export CSV': 'निर्यात CSV',
    'Global (All Categories)': 'वैश्विक (सभी श्रेणियाँ)',
    'Global Budget': 'वैश्विक बजट',
    'Google Sheets export failed: {error}': 'Google शीट निर्यात विफल: {error}',
    'Import CSV': 'CSV आयात करें',
    'Invalid OCR amount.': 'अमान्य OCR राशि।',
    'Invalid PIN.': 'अमान्य पिन.',
    'Local Database': 'स्थानीय डेटाबेस',
    'Lock Now': 'अभी लॉक करें',
    'Mark all read': 'सभी पढ़े गए को चिह्नित करें',
    'Monday': 'सोमवार',
    'Month': 'माह',
    'Monthly Limit': 'मासिक सीमा',
    'No budgets set yet.': 'अभी कोई बजट निर्धारित नहीं है।',
    'No end date': 'कोई अंतिम तिथि नहीं',
    'No planned payments yet.': 'अभी तक कोई नियोजित भुगतान नहीं।',
    'Notifications': 'सूचनाएं',
    'OCR failed or canceled.': 'OCR विफल या रद्द कर दिया गया।',
    'OCR Result': 'OCR परिणाम',
    'Offline First': 'ऑफ़लाइन प्रथम',
    'PDF export failed: {error}': 'PDF निर्यात विफल: {error}',
    'PIN': 'PIN',
    'PIN disabled.': 'पिन अक्षम।',
    'PIN enabled.': 'पिन सक्षम।',
    'PIN must be at least 4 digits.': 'पिन कम से कम 4 अंकों का होना चाहिए।',
    'Premium expense manager.\nVersion 1.0.0':
        'प्रीमियम व्यय प्रबंधक।\nसंस्करण 1.0.0',
    'Pro Lifetime - {price}': 'प्रो लाइफटाइम - {price}',
    'Process Now': 'प्रक्रिया अभी',
    'Refresh Config': 'रीफ्रेश कॉन्फिग',
    'Remote config refreshed.': 'रिमोट कॉन्फिगरेशन रीफ्रेश किया गया।',
    'Remove ads': 'विज्ञापन हटाएं',
    'Restore failed: {error}': 'पुनर्स्थापना विफल: {error}',
    'Save PIN': 'पिन सहेजें',
    'Savings target': 'बचत लक्ष्य',
    'Scan Camera': 'स्कैन कैमरा',
    'Scan Gallery': 'स्कैन गैलरी',
    'Security Lock Enabled': 'सुरक्षा लॉक सक्षम',
    'Send Event': 'इवेंट भेजें',
    'Send Test Error': 'परीक्षण त्रुटि भेजें',
    'Set PIN (4-6 digits)': 'पिन सेट करें (4-6 अंक)',
    'Smart Tools Center': 'स्मार्ट टूल्स सेंटर',
    'SMART User': 'स्मार्ट यूजर',
    'Spent': 'खर्च',
    'Sunday': 'रविवार',
    'Switch Wallet': 'स्विच वॉलेट',
    'This app is no longer maintained since November 5, 2024.\n\nYou can continue using it, but it will no longer receive updates or bug fixes. Some features may stop working over time.\n\nRecommendations:\n- Back up your data regularly.\n- Consider an actively maintained alternative.':
        'यह ऐप अब 5 नवंबर, 2024 से बनाए नहीं रखा गया है।\n\nआप कर सकते हैं इसका उपयोग जारी रखें, लेकिन इसे अब अपडेट या बग फिक्स प्राप्त नहीं होंगे। कुछ सुविधाएं समय के साथ काम करना बंद कर सकती हैं।\n\nसिफारिशें:\n- नियमित रूप से अपने डेटा का बैकअप लें।\n- सक्रिय रूप से बनाए गए विकल्प पर विचार करें।',
    'Tools': 'उपकरण',
    'Transferred {amount} {currency} between accounts.':
        'खातों के बीच {amount} {currency} स्थानांतरित किया गया।',
    'Unavailable': 'अनुपलब्ध',
    'Unlimited bank accounts (more than 2 wallets)':
        'असीमित बैंक खाते (2 से अधिक वॉलेट)',
    'Unlock with Biometrics': 'बायोमेट्रिक्स के साथ अनलॉक',
    'Unlock with biometrics or PIN to access tools.':
        'टूल तक पहुंचने के लिए बायोमेट्रिक्स या पिन के साथ अनलॉक करें।',
    'Unlock with PIN': 'पिन के साथ अनलॉक करें',
    'Upgrade to Pro to unlock OCR receipt scanner.':
        'OCR रसीद स्कैनर को अनलॉक करने के लिए प्रो में अपग्रेड करें।',
    'Use fingerprint/face to protect tools.':
        'उपकरणों की सुरक्षा के लिए फ़िंगरप्रिंट/चेहरे का उपयोग करें।',
    'Week': 'सप्ताह',
    'Usage Reached {percent}%': 'उपयोग {percent}% तक पहुंच गया',
    '{count} recurring expense(s) added automatically.':
        '{count} आवर्ती व्यय स्वचालित रूप से जोड़ा गया।',
    'Budget added for {category}.': '{category} के लिए बजट जोड़ा गया।',
    'Spent {amount} this month.': 'इस माह {amount} खर्च हुआ।',
    'You used {spent} of {limit} spendable budget.':
        'आपने खर्च करने योग्य बजट में से {limit} का {spent} उपयोग किया।',
    '{category} planned as {cadence} schedule.':
        '{category} को {cadence} शेड्यूल के रूप में नियोजित किया गया है।',
    '{target} reached {percent}%': '{target} {percent}% तक पहुंच गया',
    '{count} expense(s) synced to cloud.': '{count} व्यय क्लाउड से समन्वयित।',
    '{count} expense(s) loaded from CSV.':
        '{count} व्यय सीएसवी से लोड किया गया।',
    '{count} new expense(s) merged from cloud.':
        '{count} नए व्यय क्लाउड से विलीन हो गए।',
  },
  'zh': <String, String>{
    'Accounts, transfer, custom categories': '帐户、转账、自定义类别',
    'Add Budget': '添加预算',
    'Add Budget Goal': '添加预算目标',
    'Add Plan': '添加计划',
    'Add Planned Payment': '添加计划付款',
    'Analytics event sent.': '已发送分析事件。',
    'Backup failed: {error}': '备份失败：{error}',
    'Billing is disabled in offline mode.': '离线模式下禁用计费。',
    'Biometric authentication failed.': '生物特征认证失败。',
    'Biometric is not supported on this device.': '此设备不支持生物识别。',
    'Biometric Lock': '生物识别锁',
    'Budget check completed.': '预算检查已完成。',
    'Cadence': 'Cadence',
    'Capture runtime errors and improve app reliability.': '捕获运行时错误并提高应用程序可靠性。',
    'Check Alerts': '检查警报',
    'Choose the language used across the app': '选择应用程序中使用的语言',
    'Cloud sync and online login are disabled. The app now works fully offline with local storage.':
        '云同步和在线登录已禁用。该应用程序现在可以通过本地存储完全离线工作。',
    'Crash test logged.': '已记录碰撞测试。',
    'Crashlytics not configured yet. Add google-services.json and rebuild Android.':
        'Crashlytics 尚未配置。添加 google-services.json 并重建 Android。',
    'Create one-time or recurring plans (monthly, weekly, yearly) and process them when due.':
        '创建一次性或经常性计划（每月、每周、每年）并在到期时进行处理。',
    'CSV export failed.': 'CSV 导出失败。',
    'CSV exported.': '导出 CSV。',
    'Custom Range': '自定义范围',
    'Disable PIN': '禁用 PIN',
    'Due date': '截止日期',
    'Excel export failed: {error}': 'Excel 导出失败：{error}',
    'Expense added from OCR.': '从 OCR 添加的费用。',
    'Export CSV': '导出 CSV',
    'Global (All Categories)': '全球（所有类别）',
    'Global Budget': '全球预算',
    'Google Sheets export failed: {error}': 'Google 表格导出失败：{error}',
    'Import CSV': '导入 CSV',
    'Invalid OCR amount.': 'OCR 金额无效。',
    'Invalid PIN.': 'PIN 码无效。',
    'Local Database': '本地数据库',
    'Lock Now': '立即锁定',
    'Mark all read': '将所有标记标记为已读',
    'Monday': '周一',
    'Month': '月',
    'Monthly Limit': '每月限额',
    'No budgets set yet.': '尚未设置预算。',
    'No end date': '无结束日期',
    'No planned payments yet.': '尚无计划付款。',
    'Notifications': '通知',
    'OCR failed or canceled.': 'OCR 失败或取消。',
    'OCR Result': 'OCR 结果',
    'Offline First': '离线第一个',
    'PDF export failed: {error}': 'PDF 导出失败：{error}',
    'PIN': 'PIN',
    'PIN disabled.': 'PIN 已禁用。',
    'PIN enabled.': 'PIN 已启用。',
    'PIN must be at least 4 digits.': 'PIN 码必须至少为 4 位数字。',
    'Premium expense manager.\nVersion 1.0.0': '高级费用管理器。\n版本 1.0.0',
    'Pro Lifetime - {price}': 'Pro 生命周期 - {price}',
    'Process Now': '立即处理',
    'Refresh Config': '刷新配置',
    'Remote config refreshed.': '刷新远程配置。',
    'Remove ads': '删除广告',
    'Restore failed: {error}': '恢复失败：{error}',
    'Save PIN': '保存 PIN',
    'Savings target': '节省目标',
    'Scan Camera': '扫描相机',
    'Scan Gallery': '扫描图库',
    'Security Lock Enabled': '启用安全锁',
    'Send Event': '发送事件',
    'Send Test Error': '发送测试错误',
    'Set PIN (4-6 digits)': '设置 PIN（4-6 位）',
    'Smart Tools Center': '智能工具中心',
    'SMART User': '智能用户',
    'Spent': '已用',
    'Sunday': '周日',
    'Switch Wallet': '切换钱包',
    'This app is no longer maintained since November 5, 2024.\n\nYou can continue using it, but it will no longer receive updates or bug fixes. Some features may stop working over time.\n\nRecommendations:\n- Back up your data regularly.\n- Consider an actively maintained alternative.':
        '此应用程序自2024年11月5日起不再维护。\n\n您可以继续使用它，但它将不再接收更新或错误修复。某些功能可能会随着时间的推移而停止工作。\n\n建议：\n- 定期备份数据。\n- 考虑采用积极维护的替代方案。',
    'Tools': '工具',
    'Transferred {amount} {currency} between accounts.':
        '在帐户之间转移 {amount} {currency}。',
    'Unavailable': '不可用',
    'Unlimited bank accounts (more than 2 wallets)': '无限制银行账户（超过 2 个钱包）',
    'Unlock with Biometrics': '使用生物识别解锁',
    'Unlock with biometrics or PIN to access tools.': '使用生物识别或 PIN 解锁以访问工具。',
    'Unlock with PIN': '使用 PIN 码解锁',
    'Upgrade to Pro to unlock OCR receipt scanner.': '升级到专业版以解锁 OCR 收据扫描仪。',
    'Use fingerprint/face to protect tools.': '使用指纹/面部来保护工具。',
    'Week': '周',
    'Usage Reached {percent}%': '使用量达到{percent}%',
    '{count} recurring expense(s) added automatically.': '{count} 自动添加经常性费用。',
    'Budget added for {category}.': '添加了 {category} 的预算。',
    'Spent {amount} this month.': '这个月花了{amount}。',
    'You used {spent} of {limit} spendable budget.':
        '您使用了 {limit} 个可支出预算中的 {spent} 个。',
    '{category} planned as {cadence} schedule.':
        '{category} 计划为 {cadence} 时间表。',
    '{target} reached {percent}%': '{target} 达到 {percent}%',
    '{count} expense(s) synced to cloud.': '{count} 费用已同步到云。',
    '{count} expense(s) loaded from CSV.': '{count} 从 CSV 加载的费用。',
    '{count} new expense(s) merged from cloud.': '{count} 从云合并的新费用。',
  },
  'ja': <String, String>{
    'Accounts, transfer, custom categories': 'アカウント、転送、カスタム カテゴリ',
    'Add Budget': '予算の追加',
    'Add Budget Goal': '予算目標の追加',
    'Add Plan': '計画の追加',
    'Add Planned Payment': '計画支払いの追加',
    'Analytics event sent.': '分析イベントが送信されました。',
    'Backup failed: {error}': 'バックアップに失敗しました: {error}',
    'Billing is disabled in offline mode.': 'オフライン モードでは課金が無効になっています。',
    'Biometric authentication failed.': '生体認証に失敗しました。',
    'Biometric is not supported on this device.': 'このデバイスでは生体認証はサポートされていません。',
    'Biometric Lock': '生体認証ロック',
    'Budget check completed.': '予算チェックが完了しました。',
    'Cadence': 'ケイデンス',
    'Capture runtime errors and improve app reliability.':
        'ランタイムエラーを捕捉し、アプリの信頼性を向上させます。',
    'Check Alerts': 'アラートの確認',
    'Choose the language used across the app': 'アプリ全体で使用される言語を選択します',
    'Cloud sync and online login are disabled. The app now works fully offline with local storage.':
        'クラウド同期とオンライン ログインは無効になります。アプリはローカル ストレージを使用して完全にオフラインで動作するようになりました。',
    'Crash test logged.': 'クラッシュ テストが記録されました。',
    'Crashlytics not configured yet. Add google-services.json and rebuild Android.':
        'Crashlytics はまだ設定されていません。 google-services.json を追加して Android を再構築します。',
    'Create one-time or recurring plans (monthly, weekly, yearly) and process them when due.':
        '1 回限りの計画または定期的な計画 (月次、週次、年次) を作成し、期日になったら処理します。',
    'CSV export failed.': 'CSV エクスポートに失敗しました。',
    'CSV exported.': 'CSV がエクスポートされました。',
    'Custom Range': 'カスタム範囲',
    'Disable PIN': 'PIN を無効にする',
    'Due date': '期限',
    'Excel export failed: {error}': 'Excel エクスポートに失敗しました: {error}',
    'Expense added from OCR.': 'OCR から経費が追加されました。',
    'Export CSV': 'CSV のエクスポート',
    'Global (All Categories)': 'グローバル (すべてのカテゴリー)',
    'Global Budget': 'グローバル予算',
    'Google Sheets export failed: {error}':
        'Google スプレッドシートのエクスポートに失敗しました: {error}',
    'Import CSV': 'CSV のインポート',
    'Invalid OCR amount.': 'OCR 量が無効です。',
    'Invalid PIN.': 'PIN が無効です。',
    'Local Database': 'ローカルデータベース',
    'Lock Now': '今すぐロック',
    'Mark all read': 'すべて既読にする',
    'Monday': '月曜日',
    'Month': '月',
    'Monthly Limit': '月間制限',
    'No budgets set yet.': '予算はまだ設定されていません。',
    'No end date': '終了日はありません。',
    'No planned payments yet.': '支払いの予定はまだありません。',
    'Notifications': '通知',
    'OCR failed or canceled.': 'OCR が失敗したかキャンセルされました。',
    'OCR Result': 'OCR 結果',
    'Offline First': 'オフライン 最初',
    'PDF export failed: {error}': 'PDF エクスポートに失敗しました: {error}',
    'PIN': 'PIN',
    'PIN disabled.': 'PIN が無効です。',
    'PIN enabled.': 'PIN が有効になりました。',
    'PIN must be at least 4 digits.': 'PIN は少なくとも 4 桁である必要があります。',
    'Premium expense manager.\nVersion 1.0.0': 'プレミアム経費マネージャー。\nバージョン 1.0.0',
    'Pro Lifetime - {price}': 'Pro ライフタイム - {price}',
    'Process Now': '今すぐ処理',
    'Refresh Config': '構成の更新',
    'Remote config refreshed.': 'リモート構成が更新されました。',
    'Remove ads': '広告を削除',
    'Restore failed: {error}': '復元に失敗しました: {error}',
    'Save PIN': 'PIN を保存',
    'Savings target': '節約目標',
    'Scan Camera': 'スキャン カメラ',
    'Scan Gallery': 'スキャン ギャラリー',
    'Security Lock Enabled': 'セキュリティ ロック有効',
    'Send Event': 'イベント送信',
    'Send Test Error': 'テスト エラー送信',
    'Set PIN (4-6 digits)': 'PIN (4 ～ 6 桁) の設定',
    'Smart Tools Center': 'スマート ツール センター',
    'SMART User': 'SMART ユーザー',
    'Spent': '使用済み',
    'Sunday': '日曜日',
    'Switch Wallet': 'Switch Wallet',
    'This app is no longer maintained since November 5, 2024.\n\nYou can continue using it, but it will no longer receive updates or bug fixes. Some features may stop working over time.\n\nRecommendations:\n- Back up your data regularly.\n- Consider an actively maintained alternative.':
        'このアプリは 2024 年 11 月 5 日以降メンテナンスされなくなりました。\n\n引き続き使用できますが、アップデートやバグ修正は提供されなくなります。一部の機能は時間の経過とともに動作しなくなる可能性があります。\n\n推奨事項:\n- データを定期的にバックアップします。\n- 積極的にメンテナンスされる代替手段を検討してください。',
    'Tools': 'ツール',
    'Transferred {amount} {currency} between accounts.':
        'アカウント間で {amount} {currency} を転送しました。',
    'Unavailable': '利用不可',
    'Unlimited bank accounts (more than 2 wallets)': '無制限の銀行口座 (ウォレットが 2 つ以上)',
    'Unlock with Biometrics': '生体認証によるロック解除',
    'Unlock with biometrics or PIN to access tools.':
        '生体認証または PIN でロックを解除してツールにアクセスします。',
    'Unlock with PIN': 'PIN によるロック解除',
    'Upgrade to Pro to unlock OCR receipt scanner.':
        'OCR レシート スキャナのロックを解除するには、Pro にアップグレードします。',
    'Use fingerprint/face to protect tools.': '指紋/顔を使用してツールを保護します。',
    'Week': '週',
    'Usage Reached {percent}%': '使用量が{percent}%に達しました',
    '{count} recurring expense(s) added automatically.':
        '{count} の経常経費が自動的に追加されました。',
    'Budget added for {category}.': '{category} の予算が追加されました。',
    'Spent {amount} this month.': '今月は{amount}を費やしました。',
    'You used {spent} of {limit} spendable budget.':
        '使用可能な予算 {limit} のうち {spent} を使用しました。',
    '{category} planned as {cadence} schedule.':
        '{category} は {cadence} スケジュールとして計画されています。',
    '{target} reached {percent}%': '{target} が {percent}% に達しました',
    '{count} expense(s) synced to cloud.': '{count} 経費がクラウドに同期されました。',
    '{count} expense(s) loaded from CSV.': '{count} 経費は CSV からロードされました。',
    '{count} new expense(s) merged from cloud.': '{count} 新しい経費がクラウドから統合されました。',
  },
  'ko': <String, String>{
    'Accounts, transfer, custom categories': '계정, 이체, 사용자 정의 카테고리',
    'Add Budget': '예산 추가',
    'Add Budget Goal': '예산 목표 추가',
    'Add Plan': '계획 추가',
    'Add Planned Payment': '계획된 결제 추가',
    'Analytics event sent.': '분석 이벤트가 전송되었습니다.',
    'Backup failed: {error}': '백업 실패: {error}',
    'Billing is disabled in offline mode.': '오프라인 모드에서는 청구가 비활성화됩니다.',
    'Biometric authentication failed.': '생체 인증에 실패했습니다.',
    'Biometric is not supported on this device.': '이 장치에서는 생체 인식이 지원되지 않습니다.',
    'Biometric Lock': '생체 인식 잠금',
    'Budget check completed.': '예산 확인이 완료되었습니다.',
    'Cadence': 'Cadence',
    'Capture runtime errors and improve app reliability.':
        '런타임 오류를 포착하고 앱 안정성을 향상시킵니다.',
    'Check Alerts': '경고 확인',
    'Choose the language used across the app': '앱 전체에서 사용되는 언어를 선택하세요.',
    'Cloud sync and online login are disabled. The app now works fully offline with local storage.':
        '클라우드 동기화 및 온라인 로그인이 비활성화됩니다. 이제 앱은 로컬 저장소를 사용하여 완전히 오프라인으로 작동합니다.',
    'Crash test logged.': '충돌 테스트가 기록되었습니다.',
    'Crashlytics not configured yet. Add google-services.json and rebuild Android.':
        'Crashlytics가 아직 구성되지 않았습니다. google-services.json을 추가하고 Android를 다시 빌드합니다.',
    'Create one-time or recurring plans (monthly, weekly, yearly) and process them when due.':
        '일회성 또는 반복 계획(월간, 주간, 연간)을 만들고 마감일에 처리합니다.',
    'CSV export failed.': 'CSV 내보내기에 실패했습니다.',
    'CSV exported.': 'CSV를 내보냈습니다.',
    'Custom Range': '사용자 정의 범위',
    'Disable PIN': 'PIN 비활성화',
    'Due date': '기한',
    'Excel export failed: {error}': 'Excel 내보내기 실패: {error}',
    'Expense added from OCR.': '비용이 OCR에서 추가되었습니다.',
    'Export CSV': 'CSV 내보내기',
    'Global (All Categories)': '글로벌(모든 범주)',
    'Global Budget': '글로벌 예산',
    'Google Sheets export failed: {error}': 'Google 스프레드시트 내보내기 실패: {error}',
    'Import CSV': 'CSV 가져오기',
    'Invalid OCR amount.': 'OCR 금액이 잘못되었습니다.',
    'Invalid PIN.': 'PIN이 잘못되었습니다.',
    'Local Database': '로컬 데이터베이스',
    'Lock Now': '지금 잠금',
    'Mark all read': '모두 읽음으로 표시',
    'Monday': '월요일',
    'Month': '월',
    'Monthly Limit': '월 한도',
    'No budgets set yet.': '예산이 아직 설정되지 않았습니다.',
    'No end date': '종료 날짜 없음',
    'No planned payments yet.': '아직 계획된 지불이 없습니다.',
    'Notifications': '알림',
    'OCR failed or canceled.': 'OCR이 실패했거나 취소되었습니다.',
    'OCR Result': 'OCR 결과',
    'Offline First': '오프라인 우선',
    'PDF export failed: {error}': 'PDF 내보내기 실패: {error}',
    'PIN': 'PIN',
    'PIN disabled.': 'PIN이 비활성화되었습니다.',
    'PIN enabled.': 'PIN이 활성화되었습니다.',
    'PIN must be at least 4 digits.': 'PIN은 4자리 이상이어야 합니다.',
    'Premium expense manager.\nVersion 1.0.0': '프리미엄 비용 관리자.\n버전 1.0.0',
    'Pro Lifetime - {price}': 'Pro 평생 - {price}',
    'Process Now': '지금 처리',
    'Refresh Config': '구성 새로 고침',
    'Remote config refreshed.': '원격 구성이 새로 고쳐졌습니다.',
    'Remove ads': '광고 제거',
    'Restore failed: {error}': '복원 실패: {error}',
    'Save PIN': 'PIN 저장',
    'Savings target': '절감 목표',
    'Scan Camera': '카메라 스캔',
    'Scan Gallery': '갤러리 스캔',
    'Security Lock Enabled': '보안 잠금 활성화',
    'Send Event': '이벤트 보내기',
    'Send Test Error': '테스트 오류 보내기',
    'Set PIN (4-6 digits)': 'PIN 설정(4~6자리)',
    'Smart Tools Center': '스마트 도구 센터',
    'SMART User': 'SMART 사용자',
    'Spent': '지출',
    'Sunday': '일요일',
    'Switch Wallet': '스위치 지갑',
    'This app is no longer maintained since November 5, 2024.\n\nYou can continue using it, but it will no longer receive updates or bug fixes. Some features may stop working over time.\n\nRecommendations:\n- Back up your data regularly.\n- Consider an actively maintained alternative.':
        '이 앱은 2024년 11월 5일부터 더 이상 유지 관리되지 않습니다.\n\n계속 사용할 수는 있지만 더 이상 업데이트나 버그 수정을 받을 수 없습니다. 일부 기능은 시간이 지남에 따라 작동이 중지될 수 있습니다.\n\n권장 사항:\n- 데이터를 정기적으로 백업하십시오.\n- 적극적으로 유지 관리되는 대안을 고려하십시오.',
    'Tools': '도구',
    'Transferred {amount} {currency} between accounts.':
        '계정 간에 {amount} {currency}이(가) 전송되었습니다.',
    'Unavailable': '사용할 수 없음',
    'Unlimited bank accounts (more than 2 wallets)': '무제한 은행 계좌(지갑 2개 이상)',
    'Unlock with Biometrics': '생체 인식으로 잠금 해제',
    'Unlock with biometrics or PIN to access tools.':
        '도구에 액세스하려면 생체 인식 또는 PIN으로 잠금 해제하세요.',
    'Unlock with PIN': 'PIN으로 잠금 해제',
    'Upgrade to Pro to unlock OCR receipt scanner.':
        'Pro로 업그레이드하여 OCR 영수증 스캐너 잠금 해제.',
    'Use fingerprint/face to protect tools.': '지문/얼굴을 사용하여 도구를 보호합니다.',
    'Week': '주',
    'Usage Reached {percent}%': '사용량이 {percent}%에 도달했습니다.',
    '{count} recurring expense(s) added automatically.':
        '{count} 반복 비용이 자동으로 추가됩니다.',
    'Budget added for {category}.': '{category}에 대한 예산이 추가되었습니다.',
    'Spent {amount} this month.': '이번 달에 {amount}을(를) 지출했습니다.',
    'You used {spent} of {limit} spendable budget.':
        '{limit} 지출 가능 예산 중 {spent}을(를) 사용했습니다.',
    '{category} planned as {cadence} schedule.':
        '{category}은 {cadence} 일정으로 계획됩니다.',
    '{target} reached {percent}%': '{target}이(가) {percent}%에 도달했습니다.',
    '{count} expense(s) synced to cloud.': '{count} 비용이 클라우드에 동기화되었습니다.',
    '{count} expense(s) loaded from CSV.': '{count} 비용은 CSV에서 로드되었습니다.',
    '{count} new expense(s) merged from cloud.':
        '{count} 클라우드에서 새로운 비용이 병합되었습니다.',
  },
  'nl': <String, String>{
    'Accounts, transfer, custom categories':
        'Accounts, overdracht, aangepaste categorieën',
    'Add Budget': 'Budget toevoegen',
    'Add Budget Goal': 'Budgetdoel toevoegen',
    'Add Plan': 'Plan toevoegen',
    'Add Planned Payment': 'Geplande betaling toevoegen',
    'Analytics event sent.': 'Analytics-gebeurtenis verzonden.',
    'Backup failed: {error}': 'Back-up mislukt: {error}',
    'Billing is disabled in offline mode.':
        'Facturering is uitgeschakeld in de offlinemodus.',
    'Biometric authentication failed.': 'Biometrische authenticatie mislukt.',
    'Biometric is not supported on this device.':
        'Biometrie wordt niet ondersteund op dit apparaat.',
    'Biometric Lock': 'Biometrisch slot',
    'Budget check completed.': 'Budgetcontrole voltooid.',
    'Cadence': 'Cadans',
    'Capture runtime errors and improve app reliability.':
        'Leg runtimefouten vast en verbeter de betrouwbaarheid van de app.',
    'Check Alerts': 'Controleer waarschuwingen',
    'Choose the language used across the app':
        'Kies de taal die in de app wordt gebruikt',
    'Cloud sync and online login are disabled. The app now works fully offline with local storage.':
        'Cloudsynchronisatie en online inloggen zijn uitgeschakeld. De app werkt nu volledig offline met lokale opslag.',
    'Crash test logged.': 'Crashtest geregistreerd.',
    'Crashlytics not configured yet. Add google-services.json and rebuild Android.':
        'Crashlytics nog niet geconfigureerd. Voeg google-services.json toe en bouw Android opnieuw op.',
    'Create one-time or recurring plans (monthly, weekly, yearly) and process them when due.':
        'Maak eenmalige of terugkerende plannen (maandelijks, wekelijks, jaarlijks) en verwerk ze wanneer ze klaar zijn.',
    'CSV export failed.': 'CSV-export mislukt.',
    'CSV exported.': 'CSV geëxporteerd.',
    'Custom Range': 'Aangepast bereik',
    'Disable PIN': 'Pincode uitschakelen',
    'Due date': 'Vervaldatum',
    'Excel export failed: {error}': 'Excel-export mislukt: {error}',
    'Expense added from OCR.': 'Onkosten toegevoegd via OCR.',
    'Export CSV': 'CSV exporteren',
    'Global (All Categories)': 'Globaal (alle categorieën)',
    'Global Budget': 'Globaal budget',
    'Google Sheets export failed: {error}':
        'Exporteren naar Google Spreadsheets is mislukt: {error}',
    'Import CSV': 'CSV importeren',
    'Invalid OCR amount.': 'Ongeldig OCR-bedrag.',
    'Invalid PIN.': 'Ongeldige pincode.',
    'Local Database': 'Lokale database',
    'Lock Now': 'Nu vergrendelen',
    'Mark all read': 'Alles als gelezen markeren',
    'Monday': 'Maandag',
    'Month': 'Maand',
    'Monthly Limit': 'Maandelijkse limiet',
    'No budgets set yet.': 'Nog geen budgetten ingesteld.',
    'No end date': 'Geen einddatum',
    'No planned payments yet.': 'Nog geen geplande betalingen.',
    'Notifications': 'Meldingen',
    'OCR failed or canceled.': 'OCR mislukt of geannuleerd.',
    'OCR Result': 'OCR-resultaat',
    'Offline First': 'Offline eerst',
    'PDF export failed: {error}': 'PDF-export mislukt: {error}',
    'PIN': 'PIN',
    'PIN disabled.': 'PIN uitgeschakeld.',
    'PIN enabled.': 'PIN ingeschakeld.',
    'PIN must be at least 4 digits.':
        'De pincode moet minimaal 4 cijfers bevatten.',
    'Premium expense manager.\nVersion 1.0.0':
        'Premium Expense Manager.\nVersie 1.0.0',
    'Pro Lifetime - {price}': 'Pro Lifetime - {price}',
    'Process Now': 'Nu verwerken',
    'Refresh Config': 'Configuratie vernieuwen',
    'Remote config refreshed.': 'Configuratie op afstand vernieuwd.',
    'Remove ads': 'Advertenties verwijderen',
    'Restore failed: {error}': 'Herstellen mislukt: {error}',
    'Save PIN': 'Pincode opslaan',
    'Savings target': 'Besparingsdoel',
    'Scan Camera': 'Scancamera',
    'Scan Gallery': 'Scangalerij',
    'Security Lock Enabled': 'Veiligheidsslot ingeschakeld',
    'Send Event': 'Gebeurtenis verzenden',
    'Send Test Error': 'Testfout verzenden',
    'Set PIN (4-6 digits)': 'Pincode instellen (4-6 cijfers)',
    'Smart Tools Center': 'Smart Tools Center',
    'SMART User': 'SMART-gebruiker',
    'Spent': 'Gebruikt',
    'Sunday': 'Zondag',
    'Switch Wallet': 'Switch Wallet',
    'This app is no longer maintained since November 5, 2024.\n\nYou can continue using it, but it will no longer receive updates or bug fixes. Some features may stop working over time.\n\nRecommendations:\n- Back up your data regularly.\n- Consider an actively maintained alternative.':
        'Deze app wordt niet meer onderhouden sinds 5 november 2024.\n\nJe kunt hem blijven gebruiken, maar hij ontvangt geen updates of bugfixes meer. Sommige functies werken na verloop van tijd mogelijk niet meer.\n\nAanbevelingen:\n- Maak regelmatig een back-up van uw gegevens.\n- Overweeg een actief onderhouden alternatief.',
    'Tools': 'Tools',
    'Transferred {amount} {currency} between accounts.':
        '{amount} {currency} overgedragen tussen accounts.',
    'Unavailable': 'Niet beschikbaar',
    'Unlimited bank accounts (more than 2 wallets)':
        'Onbeperkt bankrekeningen (meer dan 2 portemonnees)',
    'Unlock with Biometrics': 'Ontgrendelen met biometrie',
    'Unlock with biometrics or PIN to access tools.':
        'Ontgrendelen met biometrie of pincode voor toegang tot tools.',
    'Unlock with PIN': 'Ontgrendelen met pincode',
    'Upgrade to Pro to unlock OCR receipt scanner.':
        'Upgrade naar Pro om de OCR-bonscanner te ontgrendelen.',
    'Use fingerprint/face to protect tools.':
        'Gebruik vingerafdruk/gezicht om gereedschappen te beschermen.',
    'Week': 'Week',
    'Usage Reached {percent}%': 'Gebruik bereikt {percent}%',
    '{count} recurring expense(s) added automatically.':
        '{count} terugkerende uitgaven worden automatisch toegevoegd.',
    'Budget added for {category}.': 'Budget toegevoegd voor {category}.',
    'Spent {amount} this month.': 'Deze maand {amount} uitgegeven.',
    'You used {spent} of {limit} spendable budget.':
        'U heeft {spent} van {limit} besteedbaar budget gebruikt.',
    '{category} planned as {cadence} schedule.':
        '{category} gepland als {cadence} schema.',
    '{target} reached {percent}%': '{target} heeft {percent}% bereikt',
    '{count} expense(s) synced to cloud.':
        '{count} uitgaven gesynchroniseerd met de cloud.',
    '{count} expense(s) loaded from CSV.':
        '{count} onkosten geladen vanuit CSV.',
    '{count} new expense(s) merged from cloud.':
        '{count} nieuwe uitgaven samengevoegd uit de cloud.',
  },
};

